"""Feature flags model.

Generated by scaffold/generate.py from specs/feature_flags.yaml.
Edit freely: regenerating keeps any file you have changed.
"""

from datetime import datetime

from sqlalchemy import Boolean, CheckConstraint, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from foundation.db import Base
from foundation.models import User, utcnow

ENVIRONMENT_OPTIONS = (
    "dev",
    "staging",
    "prod",
)
ENVIRONMENT_TONES = {"dev": "neutral", "staging": "info", "prod": "warning"}
SENSITIVE_FIELDS = ()


class FeatureFlag(Base):
    """Feature flags. Generated once, yours from here on."""

    __tablename__ = "feature_flag"
    __sensitive__ = SENSITIVE_FIELDS
    __table_args__ = (
        CheckConstraint(
            "environment IN ('dev', 'staging', 'prod')", name="ck_feature_flag_environment"
        ),
    )
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    flag_key: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(String(255), nullable=True)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    environment: Mapped[str] = mapped_column(String(64), nullable=False)
    last_modified_by_id: Mapped[int | None] = mapped_column(ForeignKey("user.id"), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
    last_modified_by: Mapped["User | None"] = relationship(
        "User", foreign_keys="FeatureFlag.last_modified_by_id", lazy="joined"
    )

    def __repr__(self) -> str:
        return f"FeatureFlag(id={self.id})"
