"""Feature flags screens.

Generated by scaffold/generate.py from specs/feature_flags.yaml.
Edit freely: regenerating keeps any file you have changed.
"""

from typing import Annotated

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from apps.feature_flags.model import ENVIRONMENT_OPTIONS, ENVIRONMENT_TONES, FeatureFlag
from foundation import audit, auth, forms
from foundation.deps import CurrentUser, DbSession
from foundation.models import User
from foundation.templating import templates

TITLE = "Feature flags"
DESCRIPTION = "Runtime switches per environment, and who last touched them."
SINGULAR = "feature flag"
MODEL = FeatureFlag

router = APIRouter(prefix="/feature-flags", tags=["feature_flags"])


def _get(session: Session, feature_flag_id: int) -> FeatureFlag:
    row = session.get(FeatureFlag, feature_flag_id)
    if row is None:
        raise HTTPException(status_code=404, detail="Feature flags: no such row")
    return row


def _columns(admin: bool) -> list[dict[str, str]]:
    """What the list view shows. Sensitive columns never reach a non-admin."""
    columns = []
    columns.append(
        {"key": "flag_key", "label": "Flag key", "kind": ("link" if not columns else "text")}
    )
    columns.append(
        {"key": "description", "label": "Description", "kind": ("link" if not columns else "text")}
    )
    columns.append(
        {"key": "enabled", "label": "Enabled", "kind": ("link" if not columns else "text")}
    )
    columns.append(
        {"key": "environment", "label": "Environment", "kind": ("link" if not columns else "badge")}
    )
    columns.append(
        {
            "key": "last_modified_by",
            "label": "Last modified by",
            "kind": ("link" if not columns else "text"),
        }
    )
    columns.append({"key": "id", "label": "ID", "kind": "id"})
    return columns


def _row(request: Request, row: FeatureFlag, admin: bool) -> dict[str, object]:
    data: dict[str, object] = {
        "flag_key": forms.display(row.flag_key),
        "description": forms.display(row.description),
        "enabled": forms.display(row.enabled),
        "environment": (
            None
            if row.environment is None
            else {
                "label": forms.display(row.environment),
                "tone": ENVIRONMENT_TONES.get(row.environment, "neutral"),
            }
        ),
        "last_modified_by": forms.display(
            row.last_modified_by.display_name if row.last_modified_by else None
        ),
    }
    ordered = {
        key: data[key]
        for key in ["flag_key", "description", "enabled", "environment", "last_modified_by"]
        if key in data
    }
    if ordered:
        first_key = next(iter(ordered))
        first_value = ordered[first_key]
        ordered[first_key] = {
            "label": first_value["label"] if isinstance(first_value, dict) else first_value,
            "href": str(request.url_for("feature_flags_detail", feature_flag_id=row.id)),
        }
    ordered["id"] = row.id
    ordered["edit_url"] = str(request.url_for("feature_flags_edit", feature_flag_id=row.id))
    return ordered


def _items(row: FeatureFlag, admin: bool) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    items.append({"label": "Flag key", "value": forms.display(row.flag_key)})
    items.append({"label": "Description", "value": forms.display(row.description)})
    items.append({"label": "Enabled", "value": forms.display(row.enabled)})
    items.append(
        {
            "label": "Environment",
            "value": (
                None
                if row.environment is None
                else {
                    "label": forms.display(row.environment),
                    "tone": ENVIRONMENT_TONES.get(row.environment, "neutral"),
                }
            ),
            "kind": "badge",
        }
    )
    items.append(
        {
            "label": "Last modified by",
            "value": forms.display(
                row.last_modified_by.display_name if row.last_modified_by else None
            ),
        }
    )
    return items


def _fields(session: Session, values: dict[str, object], admin: bool) -> list[dict[str, object]]:
    """Form fields for the generic partial. Sensitive fields are admin-only."""
    fields: list[dict[str, object]] = [
        {
            "name": "flag_key",
            "label": "Flag key",
            "value": values.get("flag_key"),
            "required": True,
            "type": "text",
        },
        {
            "name": "description",
            "label": "Description",
            "value": values.get("description"),
            "required": False,
            "type": "text",
        },
        {
            "name": "enabled",
            "label": "Enabled",
            "value": values.get("enabled"),
            "required": False,
            "type": "checkbox",
        },
        {
            "name": "environment",
            "label": "Environment",
            "value": values.get("environment"),
            "required": True,
            "type": "select",
            "options": [{"value": option, "label": option} for option in ENVIRONMENT_OPTIONS],
        },
        {
            "name": "last_modified_by_id",
            "label": "Last modified by",
            "value": values.get("last_modified_by_id"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + forms.as_options(
                session.scalars(select(User).order_by(User.display_name)), "id", "display_name"
            ),
        },
    ]
    return fields


#: Foreign keys to check before writing: (column, table, model).
_REFERENCES = (("last_modified_by_id", "user", User),)


def _check_references(session: Session, values: dict[str, object], errors: dict[str, str]) -> None:
    """A well-formed id pointing at nothing is a bad request, not an IntegrityError."""
    for column, table, model in _REFERENCES:
        value = values.get(column)
        if value is not None and session.get(model, value) is None:
            errors[column] = f"no such {table}"


def _parse(raw: dict[str, str | None], admin: bool) -> tuple[dict[str, object], dict[str, str]]:
    values: dict[str, object] = {}
    errors: dict[str, str] = {}
    forms.collect(
        values, errors, "flag_key", forms.text, raw.get("flag_key"), required=True, max_length=255
    )
    forms.collect(values, errors, "description", forms.text, raw.get("description"), max_length=255)
    values["enabled"] = forms.boolean(raw.get("enabled"))
    forms.collect(
        values,
        errors,
        "environment",
        forms.choice,
        raw.get("environment"),
        options=ENVIRONMENT_OPTIONS,
        required=True,
    )
    forms.collect(
        values, errors, "last_modified_by_id", forms.reference, raw.get("last_modified_by_id")
    )
    return values, errors


def _form_page(
    request: Request,
    session: Session,
    values: dict[str, object],
    errors: dict[str, str],
    admin: bool,
    *,
    action: str,
    heading: str,
    writable: bool = True,
    delete_url: str | None = None,
    detail_url: str | None = None,
    status_code: int = 200,
):
    return templates.TemplateResponse(
        request,
        "feature_flags/form.html",
        {
            "title": heading,
            "heading": heading,
            "action": action,
            "fields": _fields(session, values, admin),
            "errors": errors,
            "submit_label": "Save" if writable else None,
            "list_url": str(request.url_for("feature_flags_list")),
            "delete_url": delete_url if writable else None,
            "detail_url": detail_url,
        },
        status_code=status_code,
    )


@router.get("", name="feature_flags_list")
def list_rows(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
):
    admin = auth.is_admin(current_user)
    rows = session.scalars(select(FeatureFlag).order_by(FeatureFlag.id.desc())).all()
    new_url = str(request.url_for("feature_flags_new")) if auth.can_write(current_user) else None
    return templates.TemplateResponse(
        request,
        "feature_flags/list.html",
        {
            "title": TITLE,
            "columns": _columns(admin),
            "rows": [_row(request, row, admin) for row in rows],
            "actions": [{"label": "Edit", "href_key": "edit_url"}],
            "description": DESCRIPTION,
            "empty": {
                "title": "No feature flags yet",
                "text": DESCRIPTION or None,
                "cta": {"label": "New feature flag", "href": new_url} if new_url else None,
            },
            "new_url": new_url,
        },
    )


@router.get("/new", name="feature_flags_new")
def new_row(request: Request, session: DbSession, current_user: CurrentUser):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    return _form_page(
        request,
        session,
        {},
        {},
        admin,
        action=str(request.url_for("feature_flags_create")),
        heading="New feature flag",
    )


@router.post("", name="feature_flags_create")
def create_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    flag_key: Annotated[str, Form()] = "",
    description: Annotated[str, Form()] = "",
    enabled: Annotated[str, Form()] = "",
    environment: Annotated[str, Form()] = "",
    last_modified_by_id: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    values, errors = _parse(
        {
            "flag_key": flag_key,
            "description": description,
            "enabled": enabled,
            "environment": environment,
            "last_modified_by_id": last_modified_by_id,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("feature_flags_create")),
            heading="New feature flag",
            status_code=400,
        )
    row = FeatureFlag(**values)
    audit.insert(session, row)
    return RedirectResponse(
        request.url_for("feature_flags_detail", feature_flag_id=row.id), status_code=303
    )


@router.get("/{feature_flag_id}", name="feature_flags_detail")
def detail_row(
    request: Request, session: DbSession, current_user: CurrentUser, feature_flag_id: int
):
    row = _get(session, feature_flag_id)
    admin = auth.is_admin(current_user)
    return templates.TemplateResponse(
        request,
        "feature_flags/detail.html",
        {
            "title": f"{SINGULAR} {row.id}",
            "row_id": row.id,
            "items": _items(row, admin),
            "list_url": str(request.url_for("feature_flags_list")),
            "edit_url": (
                str(request.url_for("feature_flags_edit", feature_flag_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "delete_url": (
                str(request.url_for("feature_flags_delete", feature_flag_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
        },
    )


@router.get("/{feature_flag_id}/edit", name="feature_flags_edit")
def edit_row(request: Request, session: DbSession, current_user: CurrentUser, feature_flag_id: int):
    admin = auth.is_admin(current_user)
    row = _get(session, feature_flag_id)
    values = {
        "flag_key": row.flag_key,
        "description": row.description,
        "enabled": row.enabled,
        "environment": row.environment,
        "last_modified_by_id": row.last_modified_by_id,
    }
    return _form_page(
        request,
        session,
        values,
        {},
        admin,
        action=str(request.url_for("feature_flags_update", feature_flag_id=row.id)),
        heading=f"Edit feature flag {row.id}",
        writable=auth.can_write(current_user),
        delete_url=str(request.url_for("feature_flags_delete", feature_flag_id=row.id)),
        detail_url=str(request.url_for("feature_flags_detail", feature_flag_id=row.id)),
    )


@router.post("/{feature_flag_id}", name="feature_flags_update")
def update_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    feature_flag_id: int,
    flag_key: Annotated[str, Form()] = "",
    description: Annotated[str, Form()] = "",
    enabled: Annotated[str, Form()] = "",
    environment: Annotated[str, Form()] = "",
    last_modified_by_id: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    row = _get(session, feature_flag_id)
    values, errors = _parse(
        {
            "flag_key": flag_key,
            "description": description,
            "enabled": enabled,
            "environment": environment,
            "last_modified_by_id": last_modified_by_id,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("feature_flags_update", feature_flag_id=row.id)),
            heading=f"Edit feature flag {row.id}",
            delete_url=str(request.url_for("feature_flags_delete", feature_flag_id=row.id)),
            detail_url=str(request.url_for("feature_flags_detail", feature_flag_id=row.id)),
            status_code=400,
        )
    audit.update(session, row, values)
    return RedirectResponse(
        request.url_for("feature_flags_detail", feature_flag_id=row.id), status_code=303
    )


@router.post("/{feature_flag_id}/delete", name="feature_flags_delete")
def delete_row(
    request: Request, session: DbSession, current_user: CurrentUser, feature_flag_id: int
):
    auth.require_write(current_user)
    row = _get(session, feature_flag_id)
    audit.delete(session, row)
    return RedirectResponse(request.url_for("feature_flags_list"), status_code=303)
