"""Vendor contracts model.

Generated by scaffold/generate.py from specs/vendor_contracts.yaml.
Edit freely: regenerating keeps any file you have changed.
"""

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import CheckConstraint, Date, DateTime, ForeignKey, Integer, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from foundation.db import Base
from foundation.models import User, utcnow

STATUS_OPTIONS = (
    "active",
    "expiring",
    "renewed",
    "terminated",
)
STATUS_TONES = {
    "active": "success",
    "expiring": "warning",
    "renewed": "info",
    "terminated": "danger",
}
STATUS_TRANSITIONS = {}
SENSITIVE_FIELDS = ("annual_value",)


class VendorContract(Base):
    """Vendor contracts. Generated once, yours from here on."""

    __tablename__ = "vendor_contract"
    __sensitive__ = SENSITIVE_FIELDS
    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'expiring', 'renewed', 'terminated')",
            name="ck_vendor_contract_status",
        ),
    )
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    vendor_name: Mapped[str] = mapped_column(String(255), nullable=False)
    contract_ref: Mapped[str] = mapped_column(String(255), nullable=False)
    annual_value: Mapped[Decimal | None] = mapped_column(Numeric(18, 4), nullable=True)
    renewal_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    owner_id: Mapped[int | None] = mapped_column(ForeignKey("user.id"), nullable=True)
    status: Mapped[str] = mapped_column(String(64), nullable=False)
    notes: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
    owner: Mapped["User | None"] = relationship(
        "User", foreign_keys="VendorContract.owner_id", lazy="joined"
    )

    def __repr__(self) -> str:
        return f"VendorContract(id={self.id})"
