"""Vendor contracts screens.

Generated by scaffold/generate.py from specs/vendor_contracts.yaml.
Edit freely: regenerating keeps any file you have changed.
"""

from datetime import UTC, datetime
from typing import Annotated
from urllib.parse import urlencode

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from apps.vendor_contracts.model import (
    STATUS_OPTIONS,
    STATUS_TONES,
    STATUS_TRANSITIONS,
    VendorContract,
)
from foundation import audit, auth, forms
from foundation.deps import CurrentUser, DbSession
from foundation.models import AuditLog, User
from foundation.templating import templates

TITLE = "Vendor contracts"
DESCRIPTION = "Supplier agreements, their renewal dates and who owns them."
SINGULAR = "vendor contract"
MODEL = VendorContract
WORKFLOW_FIELD = "status"
OPEN_STATES = (
    "active",
    "expiring",
)
STATUS_CLOSED = (
    "renewed",
    "terminated",
)

router = APIRouter(prefix="/vendor-contracts", tags=["vendor_contracts"])


def _get(session: Session, vendor_contract_id: int) -> VendorContract:
    row = session.get(VendorContract, vendor_contract_id)
    if row is None:
        raise HTTPException(status_code=404, detail="Vendor contracts: no such row")
    return row


def _columns(admin: bool) -> list[dict[str, str]]:
    """What the list view shows. Sensitive columns never reach a non-admin."""
    columns = []
    columns.append(
        {"key": "vendor_name", "label": "Vendor name", "kind": ("link" if not columns else "text")}
    )
    columns.append(
        {
            "key": "contract_ref",
            "label": "Contract ref",
            "kind": ("link" if not columns else "text"),
        }
    )
    if admin:
        columns.append(
            {
                "key": "annual_value",
                "label": "Annual value",
                "kind": ("link" if not columns else "number"),
            }
        )
    columns.append(
        {
            "key": "renewal_date",
            "label": "Renewal date",
            "kind": ("link" if not columns else "date"),
        }
    )
    columns.append({"key": "owner", "label": "Owner", "kind": ("link" if not columns else "text")})
    columns.append(
        {"key": "status", "label": "Status", "kind": ("link" if not columns else "badge")}
    )
    columns.append({"key": "notes", "label": "Notes", "kind": ("link" if not columns else "text")})
    columns.append({"key": "id", "label": "ID", "kind": "id"})
    return columns


def _row(request: Request, row: VendorContract, admin: bool) -> dict[str, object]:
    data: dict[str, object] = {
        "vendor_name": forms.display(row.vendor_name),
        "contract_ref": forms.display(row.contract_ref),
        "renewal_date": forms.display(row.renewal_date),
        "owner": forms.display(row.owner.display_name if row.owner else None),
        "status": (
            None
            if row.status is None
            else {
                "label": forms.display(row.status),
                "tone": STATUS_TONES.get(row.status, "neutral"),
            }
        ),
        "notes": forms.display(row.notes),
    }
    if admin:
        data["annual_value"] = forms.display(row.annual_value)
    ordered = {
        key: data[key]
        for key in [
            "vendor_name",
            "contract_ref",
            "annual_value",
            "renewal_date",
            "owner",
            "status",
            "notes",
        ]
        if key in data
    }
    if ordered:
        first_key = next(iter(ordered))
        first_value = ordered[first_key]
        ordered[first_key] = {
            "label": first_value["label"] if isinstance(first_value, dict) else first_value,
            "href": str(request.url_for("vendor_contracts_detail", vendor_contract_id=row.id)),
        }
    ordered["id"] = row.id
    ordered["edit_url"] = str(request.url_for("vendor_contracts_edit", vendor_contract_id=row.id))
    return ordered


def _items(row: VendorContract, admin: bool) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    items.append({"label": "Vendor name", "value": forms.display(row.vendor_name)})
    items.append({"label": "Contract ref", "value": forms.display(row.contract_ref)})
    if admin:
        items.append({"label": "Annual value", "value": forms.display(row.annual_value)})
    items.append({"label": "Renewal date", "value": forms.display(row.renewal_date)})
    items.append(
        {"label": "Owner", "value": forms.display(row.owner.display_name if row.owner else None)}
    )
    items.append(
        {
            "label": "Status",
            "value": (
                None
                if row.status is None
                else {
                    "label": forms.display(row.status),
                    "tone": STATUS_TONES.get(row.status, "neutral"),
                }
            ),
            "kind": "badge",
        }
    )
    items.append({"label": "Notes", "value": forms.display(row.notes)})
    return items


def _fields(session: Session, values: dict[str, object], admin: bool) -> list[dict[str, object]]:
    """Form fields for the generic partial. Sensitive fields are admin-only."""
    fields: list[dict[str, object]] = [
        {
            "name": "vendor_name",
            "label": "Vendor name",
            "value": values.get("vendor_name"),
            "required": True,
            "type": "text",
        },
        {
            "name": "contract_ref",
            "label": "Contract ref",
            "value": values.get("contract_ref"),
            "required": True,
            "type": "text",
        },
        {
            "name": "renewal_date",
            "label": "Renewal date",
            "value": values.get("renewal_date"),
            "required": False,
            "type": "date",
        },
        {
            "name": "owner_id",
            "label": "Owner",
            "value": values.get("owner_id"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + forms.as_options(
                session.scalars(select(User).order_by(User.display_name)), "id", "display_name"
            ),
        },
        {
            "name": "status",
            "label": "Status",
            "value": values.get("status"),
            "required": True,
            "type": "select",
            "options": [{"value": option, "label": option} for option in STATUS_OPTIONS],
        },
        {
            "name": "notes",
            "label": "Notes",
            "value": values.get("notes"),
            "required": False,
            "type": "text",
        },
    ]
    workflow_value = values.get(WORKFLOW_FIELD)
    if workflow_value in STATUS_OPTIONS:
        workflow_options = (
            workflow_value,
            *STATUS_TRANSITIONS.get(
                workflow_value,
                tuple(option for option in STATUS_OPTIONS if option != workflow_value),
            ),
        )
        for field in fields:
            if field["name"] == WORKFLOW_FIELD:
                field["options"] = [
                    {"value": option, "label": option} for option in workflow_options
                ]
    if admin:
        fields.extend(
            [
                {
                    "name": "annual_value",
                    "label": "Annual value",
                    "value": values.get("annual_value"),
                    "required": False,
                    "type": "number",
                    "step": "any",
                },
            ]
        )
    return fields


#: Foreign keys to check before writing: (column, table, model).
_REFERENCES = (("owner_id", "user", User),)


def _check_references(session: Session, values: dict[str, object], errors: dict[str, str]) -> None:
    """A well-formed id pointing at nothing is a bad request, not an IntegrityError."""
    for column, table, model in _REFERENCES:
        value = values.get(column)
        if value is not None and session.get(model, value) is None:
            errors[column] = f"no such {table}"


def _parse(raw: dict[str, str | None], admin: bool) -> tuple[dict[str, object], dict[str, str]]:
    values: dict[str, object] = {}
    errors: dict[str, str] = {}
    forms.collect(
        values,
        errors,
        "vendor_name",
        forms.text,
        raw.get("vendor_name"),
        required=True,
        max_length=255,
    )
    forms.collect(
        values,
        errors,
        "contract_ref",
        forms.text,
        raw.get("contract_ref"),
        required=True,
        max_length=255,
    )
    forms.collect(values, errors, "renewal_date", forms.day, raw.get("renewal_date"))
    forms.collect(values, errors, "owner_id", forms.reference, raw.get("owner_id"))
    forms.collect(
        values,
        errors,
        "status",
        forms.choice,
        raw.get("status"),
        options=STATUS_OPTIONS,
        required=True,
    )
    forms.collect(values, errors, "notes", forms.text, raw.get("notes"), max_length=255)
    if admin:
        forms.collect(values, errors, "annual_value", forms.number, raw.get("annual_value"))
    return values, errors


def _form_page(
    request: Request,
    session: Session,
    values: dict[str, object],
    errors: dict[str, str],
    admin: bool,
    *,
    action: str,
    heading: str,
    writable: bool = True,
    delete_url: str | None = None,
    detail_url: str | None = None,
    status_code: int = 200,
):
    return templates.TemplateResponse(
        request,
        "vendor_contracts/form.html",
        {
            "title": heading,
            "heading": heading,
            "action": action,
            "fields": _fields(session, values, admin),
            "errors": errors,
            "submit_label": "Save" if writable else None,
            "list_url": str(request.url_for("vendor_contracts_list")),
            "delete_url": delete_url if writable else None,
            "detail_url": detail_url,
        },
        status_code=status_code,
    )


@router.get("", name="vendor_contracts_list")
def list_rows(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    state: str = "",
):
    admin = auth.is_admin(current_user)
    workflow_column = getattr(MODEL, WORKFLOW_FIELD)
    grouped = dict(
        session.execute(select(workflow_column, func.count()).group_by(workflow_column)).all()
    )
    open_count = sum(grouped.get(option, 0) for option in OPEN_STATES)
    total = sum(grouped.values())
    if state == "":
        rows = session.scalars(
            select(MODEL).where(workflow_column.in_(OPEN_STATES)).order_by(MODEL.id.asc())
        ).all()
    elif state == "all":
        rows = session.scalars(select(MODEL).order_by(MODEL.id.desc())).all()
    elif state in STATUS_OPTIONS:
        rows = session.scalars(
            select(MODEL).where(workflow_column == state).order_by(MODEL.id.desc())
        ).all()
    else:
        raise HTTPException(status_code=400, detail="invalid state")
    list_url = str(request.url_for("vendor_contracts_list"))
    tabs = [
        {"label": "Needs decision", "href": list_url, "count": open_count, "active": state == ""}
    ]
    tabs.extend(
        {
            "label": option.title(),
            "href": f"{list_url}?{urlencode({'state': option})}",
            "count": grouped.get(option, 0),
            "active": state == option,
        }
        for option in STATUS_OPTIONS
    )
    tabs.append(
        {
            "label": "All",
            "href": f"{list_url}?state=all",
            "count": total,
            "active": state == "all",
        }
    )
    today_start = datetime.now(UTC).replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=None)
    decided_today = sum(
        1
        for entry in session.scalars(
            select(AuditLog).where(
                AuditLog.table_name == MODEL.__tablename__,
                AuditLog.action == AuditLog.ACTION_UPDATE,
                AuditLog.created_at >= today_start,
            )
        )
        if (entry.after or {}).get(WORKFLOW_FIELD) in STATUS_CLOSED
        and (entry.before or {}).get(WORKFLOW_FIELD) not in STATUS_CLOSED
        and (entry.after or {}).get(WORKFLOW_FIELD) != (entry.before or {}).get(WORKFLOW_FIELD)
    )
    new_url = str(request.url_for("vendor_contracts_new")) if auth.can_write(current_user) else None
    return templates.TemplateResponse(
        request,
        "vendor_contracts/list.html",
        {
            "title": TITLE,
            "columns": _columns(admin),
            "rows": [_row(request, row, admin) for row in rows],
            "actions": [{"label": "Edit", "href_key": "edit_url"}],
            "description": DESCRIPTION,
            "empty": {
                "title": ("Nothing needs a decision" if state == "" else "No vendor contracts yet"),
                "text": (
                    f"New {SINGULAR} will appear here when they arrive."
                    if state == ""
                    else DESCRIPTION or None
                ),
                "cta": {"label": "New vendor contract", "href": new_url} if new_url else None,
            },
            "new_url": new_url,
            "stats": [
                {"label": "Waiting", "value": open_count},
                {"label": "Decided today", "value": decided_today},
                {"label": "Total", "value": total},
            ],
            "tabs": tabs,
        },
    )


@router.get("/new", name="vendor_contracts_new")
def new_row(request: Request, session: DbSession, current_user: CurrentUser):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    return _form_page(
        request,
        session,
        {},
        {},
        admin,
        action=str(request.url_for("vendor_contracts_create")),
        heading="New vendor contract",
    )


@router.post("", name="vendor_contracts_create")
def create_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    vendor_name: Annotated[str, Form()] = "",
    contract_ref: Annotated[str, Form()] = "",
    annual_value: Annotated[str, Form()] = "",
    renewal_date: Annotated[str, Form()] = "",
    owner_id: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    notes: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    values, errors = _parse(
        {
            "vendor_name": vendor_name,
            "contract_ref": contract_ref,
            "annual_value": annual_value,
            "renewal_date": renewal_date,
            "owner_id": owner_id,
            "status": status,
            "notes": notes,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("vendor_contracts_create")),
            heading="New vendor contract",
            status_code=400,
        )
    row = VendorContract(**values)
    audit.insert(session, row)
    return RedirectResponse(
        request.url_for("vendor_contracts_detail", vendor_contract_id=row.id), status_code=303
    )


@router.get("/{vendor_contract_id}", name="vendor_contracts_detail")
def detail_row(
    request: Request, session: DbSession, current_user: CurrentUser, vendor_contract_id: int
):
    row = _get(session, vendor_contract_id)
    admin = auth.is_admin(current_user)
    current_value = row.status
    current = {
        "label": current_value,
        "tone": STATUS_TONES.get(current_value, "neutral"),
    }
    decisions = [
        {"label": option.title(), "value": option, "tone": STATUS_TONES.get(option, "neutral")}
        for option in STATUS_OPTIONS
        if option
        in STATUS_TRANSITIONS.get(
            current_value,
            tuple(option for option in STATUS_OPTIONS if option != current_value),
        )
    ]
    return templates.TemplateResponse(
        request,
        "vendor_contracts/detail.html",
        {
            "title": f"{SINGULAR} {row.id}",
            "row_id": row.id,
            "items": _items(row, admin),
            "list_url": str(request.url_for("vendor_contracts_list")),
            "edit_url": (
                str(request.url_for("vendor_contracts_edit", vendor_contract_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "delete_url": (
                str(request.url_for("vendor_contracts_delete", vendor_contract_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "current": current,
            "decisions": decisions,
            "decision_url": str(
                request.url_for("vendor_contracts_decide", vendor_contract_id=row.id)
            ),
            "can_decide": auth.can_write(current_user),
        },
    )


@router.post("/{vendor_contract_id}/status", name="vendor_contracts_decide")
def decide_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    vendor_contract_id: int,
    status: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    row = _get(session, vendor_contract_id)
    if status not in STATUS_OPTIONS:
        raise HTTPException(status_code=400, detail="invalid status")
    if status not in STATUS_TRANSITIONS.get(
        row.status,
        tuple(option for option in STATUS_OPTIONS if option != row.status),
    ):
        raise HTTPException(status_code=400, detail="transition not allowed")
    audit.update(session, row, {"status": status})
    return RedirectResponse(request.url_for("vendor_contracts_list"), status_code=303)


@router.get("/{vendor_contract_id}/edit", name="vendor_contracts_edit")
def edit_row(
    request: Request, session: DbSession, current_user: CurrentUser, vendor_contract_id: int
):
    admin = auth.is_admin(current_user)
    row = _get(session, vendor_contract_id)
    values = {
        "vendor_name": row.vendor_name,
        "contract_ref": row.contract_ref,
        "annual_value": row.annual_value,
        "renewal_date": row.renewal_date,
        "owner_id": row.owner_id,
        "status": row.status,
        "notes": row.notes,
    }
    return _form_page(
        request,
        session,
        values,
        {},
        admin,
        action=str(request.url_for("vendor_contracts_update", vendor_contract_id=row.id)),
        heading=f"Edit vendor contract {row.id}",
        writable=auth.can_write(current_user),
        delete_url=str(request.url_for("vendor_contracts_delete", vendor_contract_id=row.id)),
        detail_url=str(request.url_for("vendor_contracts_detail", vendor_contract_id=row.id)),
    )


@router.post("/{vendor_contract_id}", name="vendor_contracts_update")
def update_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    vendor_contract_id: int,
    vendor_name: Annotated[str, Form()] = "",
    contract_ref: Annotated[str, Form()] = "",
    annual_value: Annotated[str, Form()] = "",
    renewal_date: Annotated[str, Form()] = "",
    owner_id: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    notes: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    row = _get(session, vendor_contract_id)
    values, errors = _parse(
        {
            "vendor_name": vendor_name,
            "contract_ref": contract_ref,
            "annual_value": annual_value,
            "renewal_date": renewal_date,
            "owner_id": owner_id,
            "status": status,
            "notes": notes,
        },
        admin,
    )
    _check_references(session, values, errors)
    if (
        WORKFLOW_FIELD in values
        and values[WORKFLOW_FIELD] != row.status
        and values[WORKFLOW_FIELD]
        not in STATUS_TRANSITIONS.get(
            row.status,
            tuple(option for option in STATUS_OPTIONS if option != row.status),
        )
    ):
        errors[WORKFLOW_FIELD] = "transition not allowed"
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("vendor_contracts_update", vendor_contract_id=row.id)),
            heading=f"Edit vendor contract {row.id}",
            delete_url=str(request.url_for("vendor_contracts_delete", vendor_contract_id=row.id)),
            detail_url=str(request.url_for("vendor_contracts_detail", vendor_contract_id=row.id)),
            status_code=400,
        )
    audit.update(session, row, values)
    return RedirectResponse(
        request.url_for("vendor_contracts_detail", vendor_contract_id=row.id), status_code=303
    )


@router.post("/{vendor_contract_id}/delete", name="vendor_contracts_delete")
def delete_row(
    request: Request, session: DbSession, current_user: CurrentUser, vendor_contract_id: int
):
    auth.require_write(current_user)
    row = _get(session, vendor_contract_id)
    audit.delete(session, row)
    return RedirectResponse(request.url_for("vendor_contracts_list"), status_code=303)
