"""Generate an app from a spec.

    uv run python scaffold/generate.py specs/<name>.yaml

Writes ``apps/<name>/`` — model, routes, templates — plus one Alembic migration
in ``migrations/versions/``. Nothing in ``foundation/`` is touched: the app is
mounted because it exists (see ``foundation/discovery.py``).

**Regenerating never overwrites your edits.** Every file the generator writes is
recorded with its hash in ``apps/<name>/.scaffold.json``. On a second run each
file is compared against that record: untouched files are refreshed, files you
have changed are left exactly as they are and reported as kept. ``--force``
overwrites anyway, and is the only way to lose work.
"""

import argparse
import ast
import hashlib
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from dataclasses import field as dataclass_field
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from foundation.config import APPS_DIR, MIGRATIONS_DIR
from scaffold import codegen
from scaffold.spec import ENUM, Spec, SpecError, load

TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
MANIFEST_NAME = ".scaffold.json"

WRITTEN = "written"
REFRESHED = "refreshed"
UNCHANGED = "unchanged"
KEPT = "kept (hand-edited)"
KEPT_FOREIGN = "kept (not mine to touch)"
KEPT_MIGRATION = "kept (migration already exists)"


@dataclass
class Result:
    app: str
    outcomes: list[tuple[Path, str]] = dataclass_field(default_factory=list)

    def add(self, path: Path, outcome: str) -> None:
        self.outcomes.append((path, outcome))

    @property
    def kept(self) -> list[Path]:
        """Files left alone because rewriting them would have destroyed work."""
        return [path for path, outcome in self.outcomes if outcome in (KEPT, KEPT_FOREIGN)]

    def report(self, root: Path) -> str:
        lines = [
            f"{outcome:<32} {path.relative_to(root)}" for path, outcome in sorted(self.outcomes)
        ]
        if self.kept:
            lines.append("")
            lines.append(
                "Kept files differ from what was generated last time, so they were left "
                "as they are. Re-run with --force to overwrite them."
            )
        return "\n".join(lines)


def build_env() -> Environment:
    """Delimiters that stay out of the way of the Jinja we are generating."""
    return Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        variable_start_string="[[",
        variable_end_string="]]",
        block_start_string="[%",
        block_end_string="%]",
        comment_start_string="[#",
        comment_end_string="#]",
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )


def render(spec: Spec, *, spec_path: Path, root: Path) -> dict[Path, str]:
    """Every file this spec produces, as path -> contents. No disk writes."""
    apps_dir = root / APPS_DIR.name
    other_model = codegen._find_app_model(spec.table_name, apps_dir)
    expected_module = f"{apps_dir.name}.{spec.app}.model"
    if other_model is not None and other_model.module != expected_module:
        other_app = other_model.module.split(".")[-2]
        raise SpecError(f"table {spec.table_name!r} already belongs to app {other_app!r}")

    revision = _revision_id(spec.app)
    migration_path = _migration_for_revision(root, revision)
    if migration_path is not None:
        migration_source = migration_path.read_text()
        if f'op.create_table(\n        "{spec.table_name}"' not in migration_source:
            raise SpecError(
                f"app {spec.app!r} already has migration {migration_path.name} creating a "
                "different table; renaming an entity needs a hand-written migration"
            )
    elif (migration_path := _migration_creating(root, spec.table_name)) is not None:
        raise SpecError(
            f"table {spec.table_name!r} is already created by {migration_path.name}; "
            "pick another entity name"
        )

    references = codegen.references_for(spec, apps_dir)
    env = build_env()
    app_dir = apps_dir / spec.app
    header_text = (
        f"Generated by scaffold/generate.py from {_relative(spec_path, root)}.\n"
        "Edit freely: regenerating keeps any file you have changed."
    )
    if spec.create_is_admin_only:
        required_sensitive = ", ".join(
            field.name for field in spec.fields if field.required and field.sensitive
        )
        header_text += (
            "\nCreating a row is admin-only: "
            f"{required_sensitive} are required but hidden from other roles."
        )

    model = env.get_template("model.py.j2").render(
        header=f'"""{spec.title} model.\n\n{header_text}\n"""',
        imports=codegen.model_imports(spec, references),
        spec=spec,
        enum_fields=[field for field in spec.fields if field.type == ENUM],
        columns=[codegen.model_column(field, references) for field in spec.fields],
        relationships=[
            codegen.model_relationship(spec, field, references)
            for field in spec.fields
            if field.is_reference
        ],
        tone_maps={
            field.name: repr(dict(field.tones)) for field in spec.fields if field.type == ENUM
        },
        table_args=[
            codegen.model_check_constraint(spec, field)
            for field in spec.fields
            if field.type == ENUM
        ],
    )

    routes = env.get_template("routes.py.j2").render(
        header=f'"""{spec.title} screens.\n\n{header_text}\n"""',
        spec=spec,
        model_imports=codegen.model_import_names(spec),
        extra_route_imports=codegen.route_imports(spec, references),
        visible_fields=spec.visible_fields,
        field_display={
            field.name: codegen.display_expression(field, references) for field in spec.fields
        },
        field_value_expressions={
            field.name: codegen.row_value_expression(spec, field, references, list_view=True)
            for field in spec.fields
        },
        detail_value_expressions={
            field.name: codegen.row_value_expression(spec, field, references)
            for field in spec.fields
        },
        field_form={
            field.name: codegen.form_field_literal(field, references) for field in spec.fields
        },
        parse_visible=[codegen.parse_line(field) for field in spec.visible_fields],
        parse_sensitive=[codegen.parse_line(field) for field in spec.sensitive_fields],
        reference_rows=codegen.reference_rows(spec, references),
        form_params=[codegen.form_param(field) for field in spec.fields],
        submitted_dict=codegen.submitted_dict(spec),
        column_kinds={field.name: codegen.column_kind(field) for field in spec.fields},
        detail_fields=spec.visible_fields,
        detail_sensitive_fields=spec.sensitive_fields,
    )

    files = {
        app_dir / "__init__.py": env.get_template("init.py.j2").render(
            header=f'"""The {spec.app} app.\n\n{header_text}\n"""'
        ),
        app_dir / "model.py": _tidy(model, "model.py"),
        app_dir / "routes.py": _tidy(routes, "routes.py"),
        app_dir / "templates" / "list.html": env.get_template("list.html.j2").render(
            spec=spec, header_text=header_text
        ),
        app_dir / "templates" / "form.html": env.get_template("form.html.j2").render(
            spec=spec, header_text=header_text
        ),
        app_dir / "templates" / "detail.html": env.get_template("detail.html.j2").render(
            spec=spec,
            header_text=header_text,
            workflow_name=spec.workflow_field.name if spec.workflow_field else "",
        ),
    }

    if migration_path is None:
        down = _current_head(root)
        files[_migration_path(spec, root, revision)] = _tidy(
            env.get_template("migration.py.j2").render(
                spec=spec,
                revision=revision,
                down_revision=down,
                down_revision_literal=repr(down) if down else "None",
                columns=[codegen.migration_column(field, references) for field in spec.fields],
                constraints=[
                    codegen.migration_constraint(spec, field)
                    for field in spec.fields
                    if field.type == ENUM
                ],
            ),
            "migration.py",
        )
    return files


def generate(spec_path: Path, *, root: Path | None = None, force: bool = False) -> Result:
    root = root or APPS_DIR.parent
    spec = load(spec_path)
    files = render(spec, spec_path=Path(spec_path), root=root)
    manifest_path = root / APPS_DIR.name / spec.app / MANIFEST_NAME
    manifest = _read_manifest(manifest_path)
    recorded: dict[str, str] = dict(manifest.get("files", {}))

    result = Result(app=spec.app)
    for path, content in files.items():
        key = _relative(path, root)
        outcome = _decide(path, content, recorded.get(key), force=force)
        if outcome in (WRITTEN, REFRESHED):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            recorded[key] = _digest(content)
        elif outcome == UNCHANGED:
            recorded[key] = _digest(content)
        result.add(path, outcome)

    migration_path = _migration_for_revision(root, _revision_id(spec.app))
    if migration_path is not None and not any(
        "migrations" in _relative(path, root) for path in files
    ):
        result.add(migration_path, KEPT_MIGRATION)

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(
            {"app": spec.app, "spec": _relative(Path(spec_path), root), "files": recorded},
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    return result


def _decide(path: Path, content: str, recorded: str | None, *, force: bool) -> str:
    if not path.exists():
        return WRITTEN
    current = path.read_text()
    if force:
        return UNCHANGED if current == content else REFRESHED
    if recorded is None:
        return KEPT_FOREIGN
    if _digest(current) != recorded:
        return KEPT
    return UNCHANGED if current == content else REFRESHED


def _tidy(source: str, filename: str) -> str:
    """Trim trailing space and collapse the blank lines the templates leave behind."""
    lines = [line.rstrip() for line in source.splitlines()]
    tidied: list[str] = []
    for line in lines:
        if not line and tidied[-2:] == ["", ""]:
            continue
        tidied.append(line)
    return _format("\n".join(tidied).strip("\n") + "\n", filename)


def _format(source: str, filename: str) -> str:
    """Best effort: with ruff around, generated code arrives already formatted.

    Formatting happens before anything is compared or written, so a file that is
    regenerated byte for byte stays 'unchanged' rather than flapping.
    """
    ruff = shutil.which("ruff")
    if ruff is None:
        return source
    for arguments in (
        ["check", "--fix-only", "--quiet", "--stdin-filename", filename, "-"],
        ["format", "--quiet", "--stdin-filename", filename, "-"],
    ):
        done = subprocess.run(
            [ruff, *arguments], input=source, capture_output=True, text=True, check=False
        )
        if done.returncode == 0 and done.stdout:
            source = done.stdout
    return source


def _digest(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()


def _relative(path: Path, root: Path) -> str:
    return str(Path(path).resolve().relative_to(root.resolve()))


def _read_manifest(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}


def _revision_id(app: str) -> str:
    """Stable per app, so regenerating never invents a second revision."""
    return hashlib.sha256(f"scaffold:{app}".encode()).hexdigest()[:12]


def _migration_path(spec: Spec, root: Path, revision: str) -> Path:
    return root / MIGRATIONS_DIR.name / "versions" / f"{revision}_create_{spec.app}.py"


def _migration_for_revision(root: Path, revision: str) -> Path | None:
    versions = root / MIGRATIONS_DIR.name / "versions"
    if not versions.is_dir():
        return None
    for path in sorted(versions.glob("*.py")):
        if revision in _revision_ids(path.read_text(), "revision"):
            return path
    return None


def _migration_creating(root: Path, table: str) -> Path | None:
    versions = root / MIGRATIONS_DIR.name / "versions"
    if not versions.is_dir():
        return None
    for path in sorted(versions.glob("*.py")):
        if f'op.create_table(\n        "{table}"' in path.read_text():
            return path
    return None


def _revision_ids(source: str, name: str) -> set[str]:
    """The strings a migration assigns to ``revision`` / ``down_revision``.

    A merge revision names several parents in a tuple, so this reads the
    assignment rather than the first quoted word after it; missing one parent
    would leave it looking like a second head forever.
    """
    try:
        module = ast.parse(source)
    except SyntaxError:
        return set()
    found: set[str] = set()
    for node in module.body:
        if not isinstance(node, ast.Assign | ast.AnnAssign):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if not any(isinstance(item, ast.Name) and item.id == name for item in targets):
            continue
        if node.value is None:
            continue
        try:
            value = ast.literal_eval(node.value)
        except (ValueError, TypeError, SyntaxError):
            continue
        if isinstance(value, str):
            found.add(value)
        elif isinstance(value, tuple | list):
            found.update(item for item in value if isinstance(item, str))
    return found


def _current_head(root: Path) -> str | None:
    """The revision nothing else points at. One linear history, one head."""
    versions = root / MIGRATIONS_DIR.name / "versions"
    revisions: set[str] = set()
    parents: set[str] = set()
    for path in sorted(versions.glob("*.py")):
        source = path.read_text()
        revisions |= _revision_ids(source, "revision")
        parents |= _revision_ids(source, "down_revision")
    heads = revisions - parents
    if len(heads) > 1:
        raise SpecError(
            f"migrations have more than one head ({', '.join(sorted(heads))}); "
            "merge them before generating"
        )
    return heads.pop() if heads else None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("spec", type=Path, help="path to the YAML spec")
    parser.add_argument(
        "--force", action="store_true", help="overwrite hand-edited files (destructive)"
    )
    args = parser.parse_args(argv)

    root = APPS_DIR.parent
    try:
        result = generate(args.spec, root=root, force=args.force)
    except SpecError as error:
        print(f"spec error: {error}", file=sys.stderr)
        return 2

    print(result.report(root))
    print("\nNext: uv run alembic upgrade head, then uv run uvicorn foundation.app:app --reload")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
