"""Widgets model.

Generated by scaffold/generate.py from specs/widgets.yaml.
Edit freely: regenerating keeps any file you have changed.
"""

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from foundation.db import Base
from foundation.models import User, utcnow

STATUS_OPTIONS = (
    "draft",
    "review",
    "done",
)
STATUS_TONES = {"draft": "neutral", "review": "warning", "done": "success"}
STATUS_TRANSITIONS = {}
SENSITIVE_FIELDS = ("internal_note",)


class Widget(Base):
    """Widgets. Generated once, yours from here on."""

    __tablename__ = "widget"
    __sensitive__ = SENSITIVE_FIELDS
    __table_args__ = (
        CheckConstraint("status IN ('draft', 'review', 'done')", name="ck_widget_status"),
    )
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    quantity: Mapped[Decimal | None] = mapped_column(Numeric(18, 4), nullable=True)
    due_on: Mapped[date | None] = mapped_column(Date, nullable=True)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    status: Mapped[str] = mapped_column(String(64), nullable=False)
    owner_id: Mapped[int | None] = mapped_column(ForeignKey("user.id"), nullable=True)
    internal_note: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
    owner: Mapped["User | None"] = relationship(
        "User", foreign_keys="Widget.owner_id", lazy="joined"
    )

    def __repr__(self) -> str:
        return f"Widget(id={self.id})"
