"""Widgets screens.

Generated by scaffold/generate.py from specs/widgets.yaml.
Edit freely: regenerating keeps any file you have changed.
"""

from datetime import UTC, datetime
from typing import Annotated
from urllib.parse import urlencode

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import func, or_, select
from sqlalchemy.orm import Session

from apps.widgets.model import STATUS_OPTIONS, STATUS_TONES, STATUS_TRANSITIONS, Widget
from foundation import audit, auth, forms
from foundation.deps import CurrentUser, DbSession
from foundation.models import AuditLog, User
from foundation.templating import templates

TITLE = "Widgets"
DESCRIPTION = "Example app generated from a neutral spec."
SINGULAR = "Widget"
MODEL = Widget
_SEARCHABLE = ("label",)
_ADMIN_SEARCHABLE = ("internal_note",)
_SORTABLE = (
    "label",
    "quantity",
    "due_on",
    "active",
    "status",
    "id",
)
_ADMIN_SORTABLE = (
    *_SORTABLE,
    "internal_note",
)
WORKFLOW_FIELD = "status"
OPEN_STATES = (
    "draft",
    "review",
)
STATUS_CLOSED = ("done",)

router = APIRouter(prefix="/widgets", tags=["widgets"])

_TOGGLEABLE = ("active",)
_SENSITIVE_TOGGLEABLE = ()


def _next_url(request: Request) -> str:
    return request.url.path + (f"?{request.url.query}" if request.url.query else "")


def _redirect_next(request: Request, next_url: str) -> RedirectResponse:
    mount_path = "/widgets"
    target = (
        next_url
        if next_url == mount_path or next_url.startswith(f"{mount_path}?")
        else str(request.url_for("widgets_list"))
    )
    return RedirectResponse(target, status_code=303)


def _decision_options(current: str) -> tuple[str, ...]:
    return STATUS_TRANSITIONS.get(
        current,
        tuple(option for option in STATUS_OPTIONS if option != current),
    )


def _get(session: Session, widget_id: int) -> Widget:
    row = session.get(Widget, widget_id)
    if row is None:
        raise HTTPException(status_code=404, detail="Widgets: no such row")
    return row


def _columns(
    request: Request,
    admin: bool,
    *,
    state: str | None,
    q: str,
    sort: str,
    direction: str,
) -> list[dict[str, object]]:
    """What the list view shows. Sensitive columns never reach a non-admin."""
    columns = []
    columns.append({"key": "label", "label": "Label", "kind": ("link" if not columns else "text")})
    columns.append(
        {"key": "quantity", "label": "Quantity", "kind": ("link" if not columns else "number")}
    )
    columns.append(
        {"key": "due_on", "label": "Due on", "kind": ("link" if not columns else "date")}
    )
    columns.append(
        {"key": "active", "label": "Active", "kind": ("link" if not columns else "toggle")}
    )
    columns.append(
        {"key": "status", "label": "Status", "kind": ("link" if not columns else "badge")}
    )
    columns.append({"key": "owner", "label": "Owner", "kind": ("link" if not columns else "text")})
    if admin:
        columns.append(
            {
                "key": "internal_note",
                "label": "Internal note",
                "kind": ("link" if not columns else "text"),
            }
        )
    columns.append({"key": "id", "label": "ID", "kind": "id"})
    sortable = _ADMIN_SORTABLE if admin else _SORTABLE
    for column in columns:
        key = column["key"]
        if key not in sortable:
            continue
        next_direction = "desc" if sort == key and direction == "asc" else "asc"
        params = {"sort": key, "dir": next_direction}
        if state is not None:
            params["state"] = state
        if q:
            params["q"] = q
        column["sort_href"] = f"{request.url.path}?{urlencode(params)}"
        if sort == key:
            column["sorted"] = direction
    return columns


def _row(
    request: Request,
    row: Widget,
    admin: bool,
    writable: bool,
    next_url: str,
) -> dict[str, object]:
    data: dict[str, object] = {
        "label": forms.display(row.label),
        "quantity": forms.display(forms.display_number(row.quantity, 2)),
        "due_on": forms.display(row.due_on),
        "active": {
            "checked": bool(row.active),
            "action": str(request.url_for("widgets_toggle", widget_id=row.id, column="active")),
            "disabled": not writable,
            "label": "On" if row.active else "Off",
            "next": next_url,
        },
        "status": (
            None
            if row.status is None
            else {
                "label": forms.display(row.status),
                "tone": STATUS_TONES.get(row.status, "neutral"),
            }
        ),
        "owner": forms.display(row.owner.display_name if row.owner else None),
    }
    if admin:
        data["internal_note"] = forms.display(row.internal_note)
    ordered = {
        key: data[key]
        for key in ["label", "quantity", "due_on", "active", "status", "owner", "internal_note"]
        if key in data
    }
    if ordered:
        first_key = next(iter(ordered))
        first_value = ordered[first_key]
        ordered[first_key] = {
            "label": first_value["label"] if isinstance(first_value, dict) else first_value,
            "href": str(request.url_for("widgets_detail", widget_id=row.id)),
        }
    ordered["id"] = row.id
    ordered["edit_url"] = str(request.url_for("widgets_edit", widget_id=row.id))
    ordered["decisions"] = (
        [
            {
                "label": option,
                "value": option,
                "tone": STATUS_TONES.get(option, "neutral"),
                "action": str(request.url_for("widgets_decide", widget_id=row.id)),
                "field": WORKFLOW_FIELD,
                "expected": row.status,
                "next": next_url,
            }
            for option in _decision_options(row.status)
        ]
        if writable
        else []
    )
    return ordered


def _items(row: Widget, admin: bool) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    items.append({"label": "Label", "value": forms.display(row.label)})
    items.append(
        {"label": "Quantity", "value": forms.display(forms.display_number(row.quantity, 2))}
    )
    items.append({"label": "Due on", "value": forms.display(row.due_on)})
    items.append(
        {
            "label": "Active",
            "value": (
                None
                if row.active is None
                else {
                    "label": "Yes" if row.active else "No",
                    "tone": "success" if row.active else "neutral",
                }
            ),
            "kind": "badge",
        }
    )
    items.append(
        {
            "label": "Status",
            "value": (
                None
                if row.status is None
                else {
                    "label": forms.display(row.status),
                    "tone": STATUS_TONES.get(row.status, "neutral"),
                }
            ),
            "kind": "badge",
        }
    )
    items.append(
        {"label": "Owner", "value": forms.display(row.owner.display_name if row.owner else None)}
    )
    if admin:
        items.append({"label": "Internal note", "value": forms.display(row.internal_note)})
    return items


def _fields(session: Session, values: dict[str, object], admin: bool) -> list[dict[str, object]]:
    """Form fields for the generic partial. Sensitive fields are admin-only."""
    fields: list[dict[str, object]] = [
        {
            "name": "label",
            "label": "Label",
            "value": values.get("label"),
            "required": True,
            "type": "text",
        },
        {
            "name": "quantity",
            "label": "Quantity",
            "value": forms.form_number(values.get("quantity"), 2),
            "required": False,
            "type": "number",
            "step": "0.01",
        },
        {
            "name": "due_on",
            "label": "Due on",
            "value": values.get("due_on"),
            "required": False,
            "type": "date",
        },
        {
            "name": "active",
            "label": "Active",
            "value": values.get("active"),
            "required": False,
            "type": "checkbox",
        },
        {
            "name": "status",
            "label": "Status",
            "value": values.get("status"),
            "required": True,
            "type": "select",
            "options": [{"value": option, "label": option} for option in STATUS_OPTIONS],
        },
        {
            "name": "owner_id",
            "label": "Owner",
            "value": values.get("owner_id"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + forms.as_options(
                session.scalars(select(User).order_by(User.display_name)), "id", "display_name"
            ),
        },
    ]
    if admin:
        fields.extend(
            [
                {
                    "name": "internal_note",
                    "label": "Internal note",
                    "value": values.get("internal_note"),
                    "required": False,
                    "type": "text",
                },
            ]
        )
    workflow_value = values.get(WORKFLOW_FIELD)
    if workflow_value in STATUS_OPTIONS:
        workflow_options = (
            workflow_value,
            *STATUS_TRANSITIONS.get(
                workflow_value,
                tuple(option for option in STATUS_OPTIONS if option != workflow_value),
            ),
        )
        for field in fields:
            if field["name"] == WORKFLOW_FIELD:
                field["options"] = [
                    {"value": option, "label": option} for option in workflow_options
                ]
    return fields


#: Foreign keys to check before writing: (column, table, model).
_REFERENCES = (("owner_id", "user", User),)


def _check_references(session: Session, values: dict[str, object], errors: dict[str, str]) -> None:
    """A well-formed id pointing at nothing is a bad request, not an IntegrityError."""
    for column, table, model in _REFERENCES:
        value = values.get(column)
        if value is not None and session.get(model, value) is None:
            errors[column] = f"no such {table}"


def _parse(raw: dict[str, str | None], admin: bool) -> tuple[dict[str, object], dict[str, str]]:
    values: dict[str, object] = {}
    errors: dict[str, str] = {}
    forms.collect(
        values, errors, "label", forms.text, raw.get("label"), required=True, max_length=255
    )
    forms.collect(values, errors, "quantity", forms.number, raw.get("quantity"), decimals=2)
    forms.collect(values, errors, "due_on", forms.day, raw.get("due_on"))
    values["active"] = forms.boolean(raw.get("active"))
    forms.collect(
        values,
        errors,
        "status",
        forms.choice,
        raw.get("status"),
        options=STATUS_OPTIONS,
        required=True,
    )
    forms.collect(values, errors, "owner_id", forms.reference, raw.get("owner_id"))
    if admin:
        forms.collect(
            values, errors, "internal_note", forms.text, raw.get("internal_note"), max_length=255
        )
    return values, errors


def _form_page(
    request: Request,
    session: Session,
    values: dict[str, object],
    errors: dict[str, str],
    admin: bool,
    *,
    action: str,
    heading: str,
    writable: bool = True,
    delete_url: str | None = None,
    detail_url: str | None = None,
    row_id: int | None = None,
    status_code: int = 200,
):
    return templates.TemplateResponse(
        request,
        "widgets/form.html",
        {
            "title": heading,
            "heading": heading,
            "action": action,
            "fields": _fields(session, values, admin),
            "errors": errors,
            "submit_label": "Save" if writable else None,
            "list_url": str(request.url_for("widgets_list")),
            "delete_url": delete_url if writable else None,
            "detail_url": detail_url,
            "row_id": row_id,
        },
        status_code=status_code,
    )


@router.get("", name="widgets_list")
def list_rows(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    state: str = "",
    q: str = "",
    sort: str = "",
    dir: str = "asc",
):
    admin = auth.is_admin(current_user)
    q = q.strip()
    searchable = _SEARCHABLE + (_ADMIN_SEARCHABLE if admin else ())
    sortable = _ADMIN_SORTABLE if admin else _SORTABLE
    normalized_sort = sort if sort in sortable else ""
    normalized_dir = dir if dir in {"asc", "desc"} else "asc"
    query = select(MODEL)
    if q and searchable:
        escaped = q.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
        pattern = f"%{escaped}%"
        query = query.where(
            or_(*(getattr(MODEL, column).ilike(pattern, escape="\\") for column in searchable))
        )
    workflow_column = getattr(MODEL, WORKFLOW_FIELD)
    grouped = dict(
        session.execute(select(workflow_column, func.count()).group_by(workflow_column)).all()
    )
    open_count = sum(grouped.get(option, 0) for option in OPEN_STATES)
    total = sum(grouped.values())
    if state == "":
        query = query.where(workflow_column.in_(OPEN_STATES))
    elif state == "all":
        pass
    elif state in STATUS_OPTIONS:
        query = query.where(workflow_column == state)
    else:
        raise HTTPException(status_code=400, detail="invalid state")
    list_url = str(request.url_for("widgets_list"))
    tabs = [
        {"label": "Needs decision", "href": list_url, "count": open_count, "active": state == ""}
    ]
    tabs.extend(
        {
            "label": option.title(),
            "href": f"{list_url}?{urlencode({'state': option})}",
            "count": grouped.get(option, 0),
            "active": state == option,
        }
        for option in STATUS_OPTIONS
    )
    tabs.append(
        {
            "label": "All",
            "href": f"{list_url}?state=all",
            "count": total,
            "active": state == "all",
        }
    )
    today_start = datetime.now(UTC).replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=None)
    decided_today = sum(
        1
        for entry in session.scalars(
            select(AuditLog).where(
                AuditLog.table_name == MODEL.__tablename__,
                AuditLog.action == AuditLog.ACTION_UPDATE,
                AuditLog.created_at >= today_start,
            )
        )
        if (entry.after or {}).get(WORKFLOW_FIELD) in STATUS_CLOSED
        and (entry.before or {}).get(WORKFLOW_FIELD) not in STATUS_CLOSED
        and (entry.after or {}).get(WORKFLOW_FIELD) != (entry.before or {}).get(WORKFLOW_FIELD)
    )
    if normalized_sort:
        sort_column = getattr(MODEL, normalized_sort)
        query = query.order_by(sort_column.asc() if normalized_dir == "asc" else sort_column.desc())
    elif state == "":
        query = query.order_by(MODEL.id.asc())
    else:
        query = query.order_by(MODEL.id.desc())
    rows = session.scalars(query).all()
    next_url = _next_url(request)
    new_url = str(request.url_for("widgets_new")) if auth.can_write(current_user) else None
    return templates.TemplateResponse(
        request,
        "widgets/list.html",
        {
            "title": TITLE,
            "columns": _columns(
                request,
                admin,
                state=state,
                q=q,
                sort=normalized_sort,
                direction=normalized_dir,
            ),
            "rows": [
                _row(request, row, admin, auth.can_write(current_user), next_url) for row in rows
            ],
            "actions": [{"label": "Edit", "href_key": "edit_url"}],
            "description": DESCRIPTION,
            "list_url": str(request.url_for("widgets_list")),
            "searchable": bool(_SEARCHABLE or (_ADMIN_SEARCHABLE if admin else ())),
            "q": q,
            "sort": normalized_sort,
            "dir": normalized_dir,
            "state": state,
            "empty": {
                "title": ("Nothing needs a decision" if state == "" else "No widgets yet"),
                "text": (
                    f"New {SINGULAR} will appear here when they arrive."
                    if state == ""
                    else DESCRIPTION or None
                ),
                "cta": {"label": "New Widget", "href": new_url} if new_url else None,
            },
            "new_url": new_url,
            "stats": [
                {"label": "Waiting", "value": open_count},
                {"label": "Decided today", "value": decided_today},
                {"label": "Total", "value": total},
            ],
            "tabs": tabs,
        },
    )


@router.get("/new", name="widgets_new")
def new_row(request: Request, session: DbSession, current_user: CurrentUser):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    return _form_page(
        request,
        session,
        {},
        {},
        admin,
        action=str(request.url_for("widgets_create")),
        heading="New Widget",
    )


@router.post("", name="widgets_create")
def create_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    label: Annotated[str, Form()] = "",
    quantity: Annotated[str, Form()] = "",
    due_on: Annotated[str, Form()] = "",
    active: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    owner_id: Annotated[str, Form()] = "",
    internal_note: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    values, errors = _parse(
        {
            "label": label,
            "quantity": quantity,
            "due_on": due_on,
            "active": active,
            "status": status,
            "owner_id": owner_id,
            "internal_note": internal_note,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("widgets_create")),
            heading="New Widget",
            status_code=400,
        )
    row = Widget(**values)
    audit.insert(session, row)
    return RedirectResponse(request.url_for("widgets_detail", widget_id=row.id), status_code=303)


@router.get("/{widget_id}", name="widgets_detail")
def detail_row(request: Request, session: DbSession, current_user: CurrentUser, widget_id: int):
    row = _get(session, widget_id)
    admin = auth.is_admin(current_user)
    current_value = row.status
    current = {
        "label": current_value,
        "tone": STATUS_TONES.get(current_value, "neutral"),
    }
    decisions = [
        {"label": option.title(), "value": option, "tone": STATUS_TONES.get(option, "neutral")}
        for option in STATUS_OPTIONS
        if option
        in STATUS_TRANSITIONS.get(
            current_value,
            tuple(option for option in STATUS_OPTIONS if option != current_value),
        )
    ]
    return templates.TemplateResponse(
        request,
        "widgets/detail.html",
        {
            "title": f"{SINGULAR} {row.id}",
            "row_id": row.id,
            "items": _items(row, admin),
            "list_url": str(request.url_for("widgets_list")),
            "edit_url": (
                str(request.url_for("widgets_edit", widget_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "delete_url": (
                str(request.url_for("widgets_delete", widget_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "current": current,
            "decisions": decisions,
            "decision_url": str(request.url_for("widgets_decide", widget_id=row.id)),
            "can_decide": auth.can_write(current_user),
        },
    )


@router.post("/{widget_id}/status", name="widgets_decide")
def decide_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    widget_id: int,
    status: Annotated[str, Form()] = "",
    expected: Annotated[str, Form()] = "",
    next: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    row = _get(session, widget_id)
    if expected and expected != row.status:
        raise HTTPException(
            status_code=409,
            detail=(
                f"this {SINGULAR} was already moved to {row.status} "
                "by someone else; reload to see it"
            ),
        )
    if status not in STATUS_OPTIONS:
        raise HTTPException(status_code=400, detail="invalid status")
    if status not in STATUS_TRANSITIONS.get(
        row.status,
        tuple(option for option in STATUS_OPTIONS if option != row.status),
    ):
        raise HTTPException(status_code=400, detail="transition not allowed")
    audit.update(session, row, {"status": status})
    return _redirect_next(request, next)


@router.post("/{widget_id}/toggle/{column}", name="widgets_toggle")
def toggle_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    widget_id: int,
    column: str,
    next: Annotated[str, Form()] = "",
):
    if column not in _TOGGLEABLE:
        raise HTTPException(status_code=404, detail="no such toggle")
    auth.require_write(current_user)
    if column in _SENSITIVE_TOGGLEABLE and not auth.is_admin(current_user):
        raise HTTPException(status_code=403, detail="admin access required")
    row = _get(session, widget_id)
    audit.update(session, row, {column: not getattr(row, column)})
    return _redirect_next(request, next)


@router.get("/{widget_id}/edit", name="widgets_edit")
def edit_row(request: Request, session: DbSession, current_user: CurrentUser, widget_id: int):
    admin = auth.is_admin(current_user)
    row = _get(session, widget_id)
    values = {
        "label": row.label,
        "quantity": row.quantity,
        "due_on": row.due_on,
        "active": row.active,
        "status": row.status,
        "owner_id": row.owner_id,
        "internal_note": row.internal_note,
    }
    return _form_page(
        request,
        session,
        values,
        {},
        admin,
        action=str(request.url_for("widgets_update", widget_id=row.id)),
        heading=f"Edit Widget {row.id}",
        writable=auth.can_write(current_user),
        delete_url=str(request.url_for("widgets_delete", widget_id=row.id)),
        detail_url=str(request.url_for("widgets_detail", widget_id=row.id)),
        row_id=row.id,
    )


@router.post("/{widget_id}", name="widgets_update")
def update_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    widget_id: int,
    label: Annotated[str, Form()] = "",
    quantity: Annotated[str, Form()] = "",
    due_on: Annotated[str, Form()] = "",
    active: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    owner_id: Annotated[str, Form()] = "",
    internal_note: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    row = _get(session, widget_id)
    values, errors = _parse(
        {
            "label": label,
            "quantity": quantity,
            "due_on": due_on,
            "active": active,
            "status": status,
            "owner_id": owner_id,
            "internal_note": internal_note,
        },
        admin,
    )
    _check_references(session, values, errors)
    if (
        WORKFLOW_FIELD in values
        and values[WORKFLOW_FIELD] != row.status
        and values[WORKFLOW_FIELD]
        not in STATUS_TRANSITIONS.get(
            row.status,
            tuple(option for option in STATUS_OPTIONS if option != row.status),
        )
    ):
        errors[WORKFLOW_FIELD] = "transition not allowed"
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("widgets_update", widget_id=row.id)),
            heading=f"Edit Widget {row.id}",
            delete_url=str(request.url_for("widgets_delete", widget_id=row.id)),
            detail_url=str(request.url_for("widgets_detail", widget_id=row.id)),
            row_id=row.id,
            status_code=400,
        )
    audit.update(session, row, values)
    return RedirectResponse(request.url_for("widgets_detail", widget_id=row.id), status_code=303)


@router.post("/{widget_id}/delete", name="widgets_delete")
def delete_row(request: Request, session: DbSession, current_user: CurrentUser, widget_id: int):
    auth.require_write(current_user)
    row = _get(session, widget_id)
    audit.delete(session, row)
    return RedirectResponse(request.url_for("widgets_list"), status_code=303)
