"""Widgets screens.

Generated by scaffold/generate.py from specs/widgets.yaml.
Edit freely: regenerating keeps any file you have changed.
"""

from typing import Annotated

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from apps.widgets.model import STATUS_OPTIONS, Widget
from foundation import audit, auth, forms
from foundation.deps import CurrentUser, DbSession
from foundation.models import User
from foundation.templating import templates

TITLE = "Widgets"

router = APIRouter(prefix="/widgets", tags=["widgets"])


def _get(session: Session, widget_id: int) -> Widget:
    row = session.get(Widget, widget_id)
    if row is None:
        raise HTTPException(status_code=404, detail="Widgets: no such row")
    return row


def _columns(admin: bool) -> list[dict[str, str]]:
    """What the list view shows. Sensitive columns never reach a non-admin."""
    columns = [{"key": "id", "label": "ID"}]
    columns.append({"key": "label", "label": "Label"})
    columns.append({"key": "quantity", "label": "Quantity"})
    columns.append({"key": "due_on", "label": "Due on"})
    columns.append({"key": "active", "label": "Active"})
    columns.append({"key": "status", "label": "Status"})
    columns.append({"key": "owner", "label": "Owner"})
    if admin:
        columns.append({"key": "internal_note", "label": "Internal note"})
    return columns


def _row(request: Request, row: Widget, admin: bool) -> dict[str, object]:
    data: dict[str, object] = {
        "id": row.id,
        "label": forms.display(row.label),
        "quantity": forms.display(row.quantity),
        "due_on": forms.display(row.due_on),
        "active": forms.display(row.active),
        "status": forms.display(row.status),
        "owner": forms.display(row.owner.display_name if row.owner else None),
        "edit_url": str(request.url_for("widgets_edit", widget_id=row.id)),
    }
    if admin:
        data["internal_note"] = forms.display(row.internal_note)
    return data


def _fields(session: Session, values: dict[str, object], admin: bool) -> list[dict[str, object]]:
    """Form fields for the generic partial. Sensitive fields are admin-only."""
    fields: list[dict[str, object]] = [
        {
            "name": "label",
            "label": "Label",
            "value": values.get("label"),
            "required": True,
            "type": "text",
        },
        {
            "name": "quantity",
            "label": "Quantity",
            "value": values.get("quantity"),
            "required": False,
            "type": "number",
        },
        {
            "name": "due_on",
            "label": "Due on",
            "value": values.get("due_on"),
            "required": False,
            "type": "date",
        },
        {
            "name": "active",
            "label": "Active",
            "value": values.get("active"),
            "required": False,
            "type": "checkbox",
        },
        {
            "name": "status",
            "label": "Status",
            "value": values.get("status"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + [{"value": option, "label": option} for option in STATUS_OPTIONS],
        },
        {
            "name": "owner_id",
            "label": "Owner",
            "value": values.get("owner_id"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + forms.as_options(
                session.scalars(select(User).order_by(User.display_name)), "id", "display_name"
            ),
        },
    ]
    if admin:
        fields.extend(
            [
                {
                    "name": "internal_note",
                    "label": "Internal note",
                    "value": values.get("internal_note"),
                    "required": False,
                    "type": "text",
                },
            ]
        )
    return fields


def _parse(raw: dict[str, str | None], admin: bool) -> tuple[dict[str, object], dict[str, str]]:
    values: dict[str, object] = {}
    errors: dict[str, str] = {}
    forms.collect(
        values, errors, "label", forms.text, raw.get("label"), required=True, max_length=255
    )
    forms.collect(values, errors, "quantity", forms.number, raw.get("quantity"))
    forms.collect(values, errors, "due_on", forms.day, raw.get("due_on"))
    values["active"] = forms.boolean(raw.get("active"))
    forms.collect(values, errors, "status", forms.choice, raw.get("status"), options=STATUS_OPTIONS)
    forms.collect(values, errors, "owner_id", forms.reference, raw.get("owner_id"))
    if admin:
        forms.collect(
            values, errors, "internal_note", forms.text, raw.get("internal_note"), max_length=255
        )
    return values, errors


def _form_page(
    request: Request,
    session: Session,
    values: dict[str, object],
    errors: dict[str, str],
    admin: bool,
    *,
    action: str,
    heading: str,
    delete_url: str | None = None,
    status_code: int = 200,
):
    return templates.TemplateResponse(
        request,
        "widgets/form.html",
        {
            "title": heading,
            "heading": heading,
            "action": action,
            "fields": _fields(session, values, admin),
            "errors": errors,
            "submit_label": "Save",
            "list_url": str(request.url_for("widgets_list")),
            "delete_url": delete_url,
        },
        status_code=status_code,
    )


@router.get("", name="widgets_list")
def list_rows(request: Request, session: DbSession, current_user: CurrentUser):
    admin = auth.is_admin(current_user)
    rows = session.scalars(select(Widget).order_by(Widget.id.desc())).all()
    return templates.TemplateResponse(
        request,
        "widgets/list.html",
        {
            "title": TITLE,
            "columns": _columns(admin),
            "rows": [_row(request, row, admin) for row in rows],
            "actions": [{"label": "Edit", "href_key": "edit_url"}],
            "empty": "No widgets yet.",
            "new_url": str(request.url_for("widgets_new")),
        },
    )


@router.get("/new", name="widgets_new")
def new_row(request: Request, session: DbSession, current_user: CurrentUser):
    admin = auth.is_admin(current_user)
    return _form_page(
        request,
        session,
        {},
        {},
        admin,
        action=str(request.url_for("widgets_create")),
        heading="New Widget",
    )


@router.post("", name="widgets_create")
def create_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    label: Annotated[str, Form()] = "",
    quantity: Annotated[str, Form()] = "",
    due_on: Annotated[str, Form()] = "",
    active: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    owner_id: Annotated[str, Form()] = "",
    internal_note: Annotated[str, Form()] = "",
):
    admin = auth.is_admin(current_user)
    values, errors = _parse(
        {
            "label": label,
            "quantity": quantity,
            "due_on": due_on,
            "active": active,
            "status": status,
            "owner_id": owner_id,
            "internal_note": internal_note,
        },
        admin,
    )
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("widgets_create")),
            heading="New Widget",
            status_code=400,
        )
    row = Widget(**values)
    audit.insert(session, row)
    return RedirectResponse(request.url_for("widgets_list"), status_code=303)


@router.get("/{widget_id}", name="widgets_edit")
def edit_row(request: Request, session: DbSession, current_user: CurrentUser, widget_id: int):
    admin = auth.is_admin(current_user)
    row = _get(session, widget_id)
    values = {
        "label": row.label,
        "quantity": row.quantity,
        "due_on": row.due_on,
        "active": row.active,
        "status": row.status,
        "owner_id": row.owner_id,
        "internal_note": row.internal_note,
    }
    return _form_page(
        request,
        session,
        values,
        {},
        admin,
        action=str(request.url_for("widgets_update", widget_id=row.id)),
        heading=f"Widget {row.id}",
        delete_url=str(request.url_for("widgets_delete", widget_id=row.id)),
    )


@router.post("/{widget_id}", name="widgets_update")
def update_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    widget_id: int,
    label: Annotated[str, Form()] = "",
    quantity: Annotated[str, Form()] = "",
    due_on: Annotated[str, Form()] = "",
    active: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    owner_id: Annotated[str, Form()] = "",
    internal_note: Annotated[str, Form()] = "",
):
    admin = auth.is_admin(current_user)
    row = _get(session, widget_id)
    values, errors = _parse(
        {
            "label": label,
            "quantity": quantity,
            "due_on": due_on,
            "active": active,
            "status": status,
            "owner_id": owner_id,
            "internal_note": internal_note,
        },
        admin,
    )
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("widgets_update", widget_id=row.id)),
            heading=f"Widget {row.id}",
            delete_url=str(request.url_for("widgets_delete", widget_id=row.id)),
            status_code=400,
        )
    audit.update(session, row, values)
    return RedirectResponse(request.url_for("widgets_list"), status_code=303)


@router.post("/{widget_id}/delete", name="widgets_delete")
def delete_row(request: Request, session: DbSession, current_user: CurrentUser, widget_id: int):
    row = _get(session, widget_id)
    audit.delete(session, row)
    return RedirectResponse(request.url_for("widgets_list"), status_code=303)
