"""create kyc_review table

Generated by scaffold/generate.py for the kyc_queue app. One migration per
app: edit it like any other migration, the generator will not rewrite it.

Revision ID: 13ebb4e4e9ca
Revises: 7f03ffc9f34f
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "13ebb4e4e9ca"
down_revision: str | None = "7f03ffc9f34f"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "kyc_review",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("customer_name", sa.String(255), nullable=False),
        sa.Column("customer_ref", sa.String(255), nullable=False),
        sa.Column("risk_score", sa.Numeric(18, 4), nullable=True),
        sa.Column("status", sa.String(64), nullable=False),
        sa.Column("submitted_on", sa.Date(), nullable=True),
        sa.Column("reviewer_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=True),
        sa.Column("notes", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'escalated')",
            name="ck_kyc_review_status",
        ),
    )


def downgrade() -> None:
    op.drop_table("kyc_review")
