"""create feature_flag table

Generated by scaffold/generate.py for the feature_flags app. One migration per
app: edit it like any other migration, the generator will not rewrite it.

Revision ID: 30ebf50c3a7e
Revises: 70450dd7f2a5
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "30ebf50c3a7e"
down_revision: str | None = "70450dd7f2a5"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "feature_flag",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("flag_key", sa.String(255), nullable=False),
        sa.Column("description", sa.String(255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("environment", sa.String(64), nullable=False),
        sa.Column("last_modified_by_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "environment IN ('dev', 'staging', 'prod')", name="ck_feature_flag_environment"
        ),
    )


def downgrade() -> None:
    op.drop_table("feature_flag")
