"""create vendor_contract table

Generated by scaffold/generate.py for the vendor_contracts app. One migration per
app: edit it like any other migration, the generator will not rewrite it.

Revision ID: 65a511914828
Revises: 30ebf50c3a7e
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65a511914828"
down_revision: str | None = "30ebf50c3a7e"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "vendor_contract",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("vendor_name", sa.String(255), nullable=False),
        sa.Column("contract_ref", sa.String(255), nullable=False),
        sa.Column("annual_value", sa.Numeric(18, 4), nullable=True),
        sa.Column("renewal_date", sa.Date(), nullable=True),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=True),
        sa.Column("status", sa.String(64), nullable=False),
        sa.Column("notes", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'expiring', 'renewed', 'terminated')",
            name="ck_vendor_contract_status",
        ),
    )


def downgrade() -> None:
    op.drop_table("vendor_contract")
