"""create refund table

Generated by scaffold/generate.py for the refunds app. One migration per
app: edit it like any other migration, the generator will not rewrite it.

Revision ID: 70450dd7f2a5
Revises: 4021419db760
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "70450dd7f2a5"
down_revision: str | None = "4021419db760"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "refund",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("transaction_ref", sa.String(255), nullable=False),
        sa.Column("customer_ref", sa.String(255), nullable=False),
        sa.Column("amount", sa.Numeric(18, 4), nullable=False),
        sa.Column("currency", sa.String(255), nullable=False),
        sa.Column("reason", sa.String(255), nullable=True),
        sa.Column("status", sa.String(64), nullable=False),
        sa.Column("requested_on", sa.Date(), nullable=True),
        sa.Column("approver_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'denied', 'processed')", name="ck_refund_status"
        ),
    )


def downgrade() -> None:
    op.drop_table("refund")
