"""create widget table

Generated by scaffold/generate.py for the widgets app. One migration per
app: edit it like any other migration, the generator will not rewrite it.

Revision ID: 7f03ffc9f34f
Revises: dadba539ba93
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7f03ffc9f34f"
down_revision: str | None = "dadba539ba93"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "widget",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("label", sa.String(255), nullable=False),
        sa.Column("quantity", sa.Numeric(18, 4), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(64), nullable=True),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=True),
        sa.Column("internal_note", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('draft', 'review', 'done')", name="ck_widget_status"
        ),
    )


def downgrade() -> None:
    op.drop_table("widget")
