"""The kyc_queue app.

Generated by scaffold/generate.py from specs/kyc_queue.yaml.
Edit freely: regenerating keeps any file you have changed.
Creating a row is admin-only: customer_name, customer_ref are required but hidden from other roles.
"""
