"""KYC review queue model.

Generated by scaffold/generate.py from specs/kyc_queue.yaml.
Edit freely: regenerating keeps any file you have changed.
Creating a row is admin-only: customer_name, customer_ref are required but hidden from other roles.
"""

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import CheckConstraint, Date, DateTime, ForeignKey, Integer, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from foundation.db import Base
from foundation.models import User, utcnow

STATUS_OPTIONS = (
    "pending",
    "approved",
    "rejected",
    "escalated",
)
STATUS_TONES = {
    "pending": "warning",
    "approved": "success",
    "rejected": "danger",
    "escalated": "info",
}
SENSITIVE_FIELDS = (
    "customer_name",
    "customer_ref",
)


class KycReview(Base):
    """KYC review queue. Generated once, yours from here on."""

    __tablename__ = "kyc_review"
    __sensitive__ = SENSITIVE_FIELDS
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'escalated')",
            name="ck_kyc_review_status",
        ),
    )
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    customer_name: Mapped[str] = mapped_column(String(255), nullable=False)
    customer_ref: Mapped[str] = mapped_column(String(255), nullable=False)
    risk_score: Mapped[Decimal | None] = mapped_column(Numeric(18, 4), nullable=True)
    status: Mapped[str] = mapped_column(String(64), nullable=False)
    submitted_on: Mapped[date | None] = mapped_column(Date, nullable=True)
    reviewer_id: Mapped[int | None] = mapped_column(ForeignKey("user.id"), nullable=True)
    notes: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, nullable=False)
    reviewer: Mapped["User | None"] = relationship(
        "User", foreign_keys="KycReview.reviewer_id", lazy="joined"
    )

    def __repr__(self) -> str:
        return f"KycReview(id={self.id})"
