"""KYC review queue screens.

Generated by scaffold/generate.py from specs/kyc_queue.yaml.
Edit freely: regenerating keeps any file you have changed.
Creating a row is admin-only: customer_name, customer_ref are required but hidden from other roles.
"""

from typing import Annotated

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from apps.kyc_queue.model import STATUS_OPTIONS, KycReview
from foundation import audit, auth, forms
from foundation.deps import CurrentUser, DbSession
from foundation.models import User
from foundation.templating import templates

TITLE = "KYC review queue"

router = APIRouter(prefix="/kyc-queue", tags=["kyc_queue"])


def _get(session: Session, kyc_review_id: int) -> KycReview:
    row = session.get(KycReview, kyc_review_id)
    if row is None:
        raise HTTPException(status_code=404, detail="KYC review queue: no such row")
    return row


def _columns(admin: bool) -> list[dict[str, str]]:
    """What the list view shows. Sensitive columns never reach a non-admin."""
    columns = [{"key": "id", "label": "ID"}]
    columns.append({"key": "risk_score", "label": "Risk score"})
    columns.append({"key": "status", "label": "Status"})
    columns.append({"key": "submitted_on", "label": "Submitted on"})
    columns.append({"key": "reviewer", "label": "Reviewer"})
    columns.append({"key": "notes", "label": "Notes"})
    if admin:
        columns.append({"key": "customer_name", "label": "Customer name"})
        columns.append({"key": "customer_ref", "label": "Customer ref"})
    return columns


def _row(request: Request, row: KycReview, admin: bool) -> dict[str, object]:
    data: dict[str, object] = {
        "id": row.id,
        "risk_score": forms.display(row.risk_score),
        "status": forms.display(row.status),
        "submitted_on": forms.display(row.submitted_on),
        "reviewer": forms.display(row.reviewer.display_name if row.reviewer else None),
        "notes": forms.display(row.notes),
        "edit_url": str(request.url_for("kyc_queue_edit", kyc_review_id=row.id)),
    }
    if admin:
        data["customer_name"] = forms.display(row.customer_name)
        data["customer_ref"] = forms.display(row.customer_ref)
    return data


def _fields(session: Session, values: dict[str, object], admin: bool) -> list[dict[str, object]]:
    """Form fields for the generic partial. Sensitive fields are admin-only."""
    fields: list[dict[str, object]] = [
        {
            "name": "risk_score",
            "label": "Risk score",
            "value": values.get("risk_score"),
            "required": False,
            "type": "number",
            "step": "any",
        },
        {
            "name": "status",
            "label": "Status",
            "value": values.get("status"),
            "required": True,
            "type": "select",
            "options": [{"value": option, "label": option} for option in STATUS_OPTIONS],
        },
        {
            "name": "submitted_on",
            "label": "Submitted on",
            "value": values.get("submitted_on"),
            "required": False,
            "type": "date",
        },
        {
            "name": "reviewer_id",
            "label": "Reviewer",
            "value": values.get("reviewer_id"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + forms.as_options(
                session.scalars(select(User).order_by(User.display_name)), "id", "display_name"
            ),
        },
        {
            "name": "notes",
            "label": "Notes",
            "value": values.get("notes"),
            "required": False,
            "type": "text",
        },
    ]
    if admin:
        fields.extend(
            [
                {
                    "name": "customer_name",
                    "label": "Customer name",
                    "value": values.get("customer_name"),
                    "required": True,
                    "type": "text",
                },
                {
                    "name": "customer_ref",
                    "label": "Customer ref",
                    "value": values.get("customer_ref"),
                    "required": True,
                    "type": "text",
                },
            ]
        )
    return fields


#: Foreign keys to check before writing: (column, table, model).
_REFERENCES = (("reviewer_id", "user", User),)


def _check_references(session: Session, values: dict[str, object], errors: dict[str, str]) -> None:
    """A well-formed id pointing at nothing is a bad request, not an IntegrityError."""
    for column, table, model in _REFERENCES:
        value = values.get(column)
        if value is not None and session.get(model, value) is None:
            errors[column] = f"no such {table}"


def _parse(raw: dict[str, str | None], admin: bool) -> tuple[dict[str, object], dict[str, str]]:
    values: dict[str, object] = {}
    errors: dict[str, str] = {}
    forms.collect(values, errors, "risk_score", forms.number, raw.get("risk_score"))
    forms.collect(
        values,
        errors,
        "status",
        forms.choice,
        raw.get("status"),
        options=STATUS_OPTIONS,
        required=True,
    )
    forms.collect(values, errors, "submitted_on", forms.day, raw.get("submitted_on"))
    forms.collect(values, errors, "reviewer_id", forms.reference, raw.get("reviewer_id"))
    forms.collect(values, errors, "notes", forms.text, raw.get("notes"), max_length=255)
    if admin:
        forms.collect(
            values,
            errors,
            "customer_name",
            forms.text,
            raw.get("customer_name"),
            required=True,
            max_length=255,
        )
        forms.collect(
            values,
            errors,
            "customer_ref",
            forms.text,
            raw.get("customer_ref"),
            required=True,
            max_length=255,
        )
    return values, errors


def _form_page(
    request: Request,
    session: Session,
    values: dict[str, object],
    errors: dict[str, str],
    admin: bool,
    *,
    action: str,
    heading: str,
    writable: bool = True,
    delete_url: str | None = None,
    status_code: int = 200,
):
    return templates.TemplateResponse(
        request,
        "kyc_queue/form.html",
        {
            "title": heading,
            "heading": heading,
            "action": action,
            "fields": _fields(session, values, admin),
            "errors": errors,
            "submit_label": "Save" if writable else None,
            "list_url": str(request.url_for("kyc_queue_list")),
            "delete_url": delete_url if writable else None,
        },
        status_code=status_code,
    )


@router.get("", name="kyc_queue_list")
def list_rows(request: Request, session: DbSession, current_user: CurrentUser):
    admin = auth.is_admin(current_user)
    rows = session.scalars(select(KycReview).order_by(KycReview.id.desc())).all()
    return templates.TemplateResponse(
        request,
        "kyc_queue/list.html",
        {
            "title": TITLE,
            "columns": _columns(admin),
            "rows": [_row(request, row, admin) for row in rows],
            "actions": [{"label": "Edit", "href_key": "edit_url"}],
            "empty": "No kyc review queue yet.",
            "new_url": (
                str(request.url_for("kyc_queue_new")) if auth.is_admin(current_user) else None
            ),
        },
    )


@router.get("/new", name="kyc_queue_new")
def new_row(request: Request, session: DbSession, current_user: CurrentUser):
    auth.require_admin(current_user)
    admin = auth.is_admin(current_user)
    return _form_page(
        request,
        session,
        {},
        {},
        admin,
        action=str(request.url_for("kyc_queue_create")),
        heading="New Kyc review",
    )


@router.post("", name="kyc_queue_create")
def create_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    customer_name: Annotated[str, Form()] = "",
    customer_ref: Annotated[str, Form()] = "",
    risk_score: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    submitted_on: Annotated[str, Form()] = "",
    reviewer_id: Annotated[str, Form()] = "",
    notes: Annotated[str, Form()] = "",
):
    auth.require_admin(current_user)
    admin = auth.is_admin(current_user)
    values, errors = _parse(
        {
            "customer_name": customer_name,
            "customer_ref": customer_ref,
            "risk_score": risk_score,
            "status": status,
            "submitted_on": submitted_on,
            "reviewer_id": reviewer_id,
            "notes": notes,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("kyc_queue_create")),
            heading="New Kyc review",
            status_code=400,
        )
    row = KycReview(**values)
    audit.insert(session, row)
    return RedirectResponse(request.url_for("kyc_queue_list"), status_code=303)


@router.get("/{kyc_review_id}", name="kyc_queue_edit")
def edit_row(request: Request, session: DbSession, current_user: CurrentUser, kyc_review_id: int):
    admin = auth.is_admin(current_user)
    row = _get(session, kyc_review_id)
    values = {
        "customer_name": row.customer_name,
        "customer_ref": row.customer_ref,
        "risk_score": row.risk_score,
        "status": row.status,
        "submitted_on": row.submitted_on,
        "reviewer_id": row.reviewer_id,
        "notes": row.notes,
    }
    return _form_page(
        request,
        session,
        values,
        {},
        admin,
        action=str(request.url_for("kyc_queue_update", kyc_review_id=row.id)),
        heading=f"Kyc review {row.id}",
        writable=auth.can_write(current_user),
        delete_url=str(request.url_for("kyc_queue_delete", kyc_review_id=row.id)),
    )


@router.post("/{kyc_review_id}", name="kyc_queue_update")
def update_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    kyc_review_id: int,
    customer_name: Annotated[str, Form()] = "",
    customer_ref: Annotated[str, Form()] = "",
    risk_score: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    submitted_on: Annotated[str, Form()] = "",
    reviewer_id: Annotated[str, Form()] = "",
    notes: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    row = _get(session, kyc_review_id)
    values, errors = _parse(
        {
            "customer_name": customer_name,
            "customer_ref": customer_ref,
            "risk_score": risk_score,
            "status": status,
            "submitted_on": submitted_on,
            "reviewer_id": reviewer_id,
            "notes": notes,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("kyc_queue_update", kyc_review_id=row.id)),
            heading=f"Kyc review {row.id}",
            delete_url=str(request.url_for("kyc_queue_delete", kyc_review_id=row.id)),
            status_code=400,
        )
    audit.update(session, row, values)
    return RedirectResponse(request.url_for("kyc_queue_list"), status_code=303)


@router.post("/{kyc_review_id}/delete", name="kyc_queue_delete")
def delete_row(request: Request, session: DbSession, current_user: CurrentUser, kyc_review_id: int):
    auth.require_write(current_user)
    row = _get(session, kyc_review_id)
    audit.delete(session, row)
    return RedirectResponse(request.url_for("kyc_queue_list"), status_code=303)
