"""KYC review queue screens.

Generated by scaffold/generate.py from specs/kyc_queue.yaml.
Edit freely: regenerating keeps any file you have changed.
Creating a row is admin-only: customer_name, customer_ref are required but hidden from other roles.
"""

from datetime import UTC, datetime
from typing import Annotated
from urllib.parse import urlencode

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from apps.kyc_queue.model import STATUS_OPTIONS, STATUS_TONES, STATUS_TRANSITIONS, KycReview
from foundation import audit, auth, forms
from foundation.deps import CurrentUser, DbSession
from foundation.models import AuditLog, User
from foundation.templating import templates

TITLE = "KYC review queue"
DESCRIPTION = "Customer due-diligence cases waiting for a reviewer's decision."
SINGULAR = "KYC review"
MODEL = KycReview
WORKFLOW_FIELD = "status"
OPEN_STATES = (
    "pending",
    "escalated",
)
STATUS_CLOSED = (
    "approved",
    "rejected",
)

router = APIRouter(prefix="/kyc-queue", tags=["kyc_queue"])


def _get(session: Session, kyc_review_id: int) -> KycReview:
    row = session.get(KycReview, kyc_review_id)
    if row is None:
        raise HTTPException(status_code=404, detail="KYC review queue: no such row")
    return row


def _columns(admin: bool) -> list[dict[str, str]]:
    """What the list view shows. Sensitive columns never reach a non-admin."""
    columns = []
    if admin:
        columns.append(
            {
                "key": "customer_name",
                "label": "Customer name",
                "kind": ("link" if not columns else "text"),
            }
        )
    if admin:
        columns.append(
            {
                "key": "customer_ref",
                "label": "Customer ref",
                "kind": ("link" if not columns else "text"),
            }
        )
    columns.append(
        {"key": "risk_score", "label": "Risk score", "kind": ("link" if not columns else "number")}
    )
    columns.append(
        {"key": "status", "label": "Status", "kind": ("link" if not columns else "badge")}
    )
    columns.append(
        {
            "key": "submitted_on",
            "label": "Submitted on",
            "kind": ("link" if not columns else "date"),
        }
    )
    columns.append(
        {"key": "reviewer", "label": "Reviewer", "kind": ("link" if not columns else "text")}
    )
    columns.append({"key": "notes", "label": "Notes", "kind": ("link" if not columns else "text")})
    columns.append({"key": "id", "label": "ID", "kind": "id"})
    return columns


def _row(request: Request, row: KycReview, admin: bool) -> dict[str, object]:
    data: dict[str, object] = {
        "risk_score": forms.display(row.risk_score),
        "status": (
            None
            if row.status is None
            else {
                "label": forms.display(row.status),
                "tone": STATUS_TONES.get(row.status, "neutral"),
            }
        ),
        "submitted_on": forms.display(row.submitted_on),
        "reviewer": forms.display(row.reviewer.display_name if row.reviewer else None),
        "notes": forms.display(row.notes),
    }
    if admin:
        data["customer_name"] = forms.display(row.customer_name)
        data["customer_ref"] = forms.display(row.customer_ref)
    ordered = {
        key: data[key]
        for key in [
            "customer_name",
            "customer_ref",
            "risk_score",
            "status",
            "submitted_on",
            "reviewer",
            "notes",
        ]
        if key in data
    }
    if ordered:
        first_key = next(iter(ordered))
        first_value = ordered[first_key]
        ordered[first_key] = {
            "label": first_value["label"] if isinstance(first_value, dict) else first_value,
            "href": str(request.url_for("kyc_queue_detail", kyc_review_id=row.id)),
        }
    ordered["id"] = row.id
    ordered["edit_url"] = str(request.url_for("kyc_queue_edit", kyc_review_id=row.id))
    return ordered


def _items(row: KycReview, admin: bool) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    if admin:
        items.append({"label": "Customer name", "value": forms.display(row.customer_name)})
    if admin:
        items.append({"label": "Customer ref", "value": forms.display(row.customer_ref)})
    items.append({"label": "Risk score", "value": forms.display(row.risk_score)})
    items.append(
        {
            "label": "Status",
            "value": (
                None
                if row.status is None
                else {
                    "label": forms.display(row.status),
                    "tone": STATUS_TONES.get(row.status, "neutral"),
                }
            ),
            "kind": "badge",
        }
    )
    items.append({"label": "Submitted on", "value": forms.display(row.submitted_on)})
    items.append(
        {
            "label": "Reviewer",
            "value": forms.display(row.reviewer.display_name if row.reviewer else None),
        }
    )
    items.append({"label": "Notes", "value": forms.display(row.notes)})
    return items


def _fields(session: Session, values: dict[str, object], admin: bool) -> list[dict[str, object]]:
    """Form fields for the generic partial. Sensitive fields are admin-only."""
    fields: list[dict[str, object]] = [
        {
            "name": "risk_score",
            "label": "Risk score",
            "value": values.get("risk_score"),
            "required": False,
            "type": "number",
            "step": "any",
        },
        {
            "name": "status",
            "label": "Status",
            "value": values.get("status"),
            "required": True,
            "type": "select",
            "options": [{"value": option, "label": option} for option in STATUS_OPTIONS],
        },
        {
            "name": "submitted_on",
            "label": "Submitted on",
            "value": values.get("submitted_on"),
            "required": False,
            "type": "date",
        },
        {
            "name": "reviewer_id",
            "label": "Reviewer",
            "value": values.get("reviewer_id"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + forms.as_options(
                session.scalars(select(User).order_by(User.display_name)), "id", "display_name"
            ),
        },
        {
            "name": "notes",
            "label": "Notes",
            "value": values.get("notes"),
            "required": False,
            "type": "text",
        },
    ]
    workflow_value = values.get(WORKFLOW_FIELD)
    if workflow_value in STATUS_OPTIONS:
        workflow_options = (
            workflow_value,
            *STATUS_TRANSITIONS.get(
                workflow_value,
                tuple(option for option in STATUS_OPTIONS if option != workflow_value),
            ),
        )
        for field in fields:
            if field["name"] == WORKFLOW_FIELD:
                field["options"] = [
                    {"value": option, "label": option} for option in workflow_options
                ]
    if admin:
        fields.extend(
            [
                {
                    "name": "customer_name",
                    "label": "Customer name",
                    "value": values.get("customer_name"),
                    "required": True,
                    "type": "text",
                },
                {
                    "name": "customer_ref",
                    "label": "Customer ref",
                    "value": values.get("customer_ref"),
                    "required": True,
                    "type": "text",
                },
            ]
        )
    return fields


#: Foreign keys to check before writing: (column, table, model).
_REFERENCES = (("reviewer_id", "user", User),)


def _check_references(session: Session, values: dict[str, object], errors: dict[str, str]) -> None:
    """A well-formed id pointing at nothing is a bad request, not an IntegrityError."""
    for column, table, model in _REFERENCES:
        value = values.get(column)
        if value is not None and session.get(model, value) is None:
            errors[column] = f"no such {table}"


def _parse(raw: dict[str, str | None], admin: bool) -> tuple[dict[str, object], dict[str, str]]:
    values: dict[str, object] = {}
    errors: dict[str, str] = {}
    forms.collect(values, errors, "risk_score", forms.number, raw.get("risk_score"))
    forms.collect(
        values,
        errors,
        "status",
        forms.choice,
        raw.get("status"),
        options=STATUS_OPTIONS,
        required=True,
    )
    forms.collect(values, errors, "submitted_on", forms.day, raw.get("submitted_on"))
    forms.collect(values, errors, "reviewer_id", forms.reference, raw.get("reviewer_id"))
    forms.collect(values, errors, "notes", forms.text, raw.get("notes"), max_length=255)
    if admin:
        forms.collect(
            values,
            errors,
            "customer_name",
            forms.text,
            raw.get("customer_name"),
            required=True,
            max_length=255,
        )
        forms.collect(
            values,
            errors,
            "customer_ref",
            forms.text,
            raw.get("customer_ref"),
            required=True,
            max_length=255,
        )
    return values, errors


def _form_page(
    request: Request,
    session: Session,
    values: dict[str, object],
    errors: dict[str, str],
    admin: bool,
    *,
    action: str,
    heading: str,
    writable: bool = True,
    delete_url: str | None = None,
    detail_url: str | None = None,
    status_code: int = 200,
):
    return templates.TemplateResponse(
        request,
        "kyc_queue/form.html",
        {
            "title": heading,
            "heading": heading,
            "action": action,
            "fields": _fields(session, values, admin),
            "errors": errors,
            "submit_label": "Save" if writable else None,
            "list_url": str(request.url_for("kyc_queue_list")),
            "delete_url": delete_url if writable else None,
            "detail_url": detail_url,
        },
        status_code=status_code,
    )


@router.get("", name="kyc_queue_list")
def list_rows(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    state: str = "",
):
    admin = auth.is_admin(current_user)
    workflow_column = getattr(MODEL, WORKFLOW_FIELD)
    grouped = dict(
        session.execute(select(workflow_column, func.count()).group_by(workflow_column)).all()
    )
    open_count = sum(grouped.get(option, 0) for option in OPEN_STATES)
    total = sum(grouped.values())
    if state == "":
        rows = session.scalars(
            select(MODEL).where(workflow_column.in_(OPEN_STATES)).order_by(MODEL.id.asc())
        ).all()
    elif state == "all":
        rows = session.scalars(select(MODEL).order_by(MODEL.id.desc())).all()
    elif state in STATUS_OPTIONS:
        rows = session.scalars(
            select(MODEL).where(workflow_column == state).order_by(MODEL.id.desc())
        ).all()
    else:
        raise HTTPException(status_code=400, detail="invalid state")
    list_url = str(request.url_for("kyc_queue_list"))
    tabs = [
        {"label": "Needs decision", "href": list_url, "count": open_count, "active": state == ""}
    ]
    tabs.extend(
        {
            "label": option.title(),
            "href": f"{list_url}?{urlencode({'state': option})}",
            "count": grouped.get(option, 0),
            "active": state == option,
        }
        for option in STATUS_OPTIONS
    )
    tabs.append(
        {
            "label": "All",
            "href": f"{list_url}?state=all",
            "count": total,
            "active": state == "all",
        }
    )
    today_start = datetime.now(UTC).replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=None)
    decided_today = sum(
        1
        for entry in session.scalars(
            select(AuditLog).where(
                AuditLog.table_name == MODEL.__tablename__,
                AuditLog.action == AuditLog.ACTION_UPDATE,
                AuditLog.created_at >= today_start,
            )
        )
        if (entry.after or {}).get(WORKFLOW_FIELD) in STATUS_CLOSED
        and (entry.before or {}).get(WORKFLOW_FIELD) not in STATUS_CLOSED
        and (entry.after or {}).get(WORKFLOW_FIELD) != (entry.before or {}).get(WORKFLOW_FIELD)
    )
    new_url = str(request.url_for("kyc_queue_new")) if auth.is_admin(current_user) else None
    return templates.TemplateResponse(
        request,
        "kyc_queue/list.html",
        {
            "title": TITLE,
            "columns": _columns(admin),
            "rows": [_row(request, row, admin) for row in rows],
            "actions": [{"label": "Edit", "href_key": "edit_url"}],
            "description": DESCRIPTION,
            "empty": {
                "title": ("Nothing needs a decision" if state == "" else "No kyc review queue yet"),
                "text": (
                    f"New {SINGULAR} will appear here when they arrive."
                    if state == ""
                    else DESCRIPTION or None
                ),
                "cta": {"label": "New KYC review", "href": new_url} if new_url else None,
            },
            "new_url": new_url,
            "stats": [
                {"label": "Waiting", "value": open_count},
                {"label": "Decided today", "value": decided_today},
                {"label": "Total", "value": total},
            ],
            "tabs": tabs,
        },
    )


@router.get("/new", name="kyc_queue_new")
def new_row(request: Request, session: DbSession, current_user: CurrentUser):
    auth.require_admin(current_user)
    admin = auth.is_admin(current_user)
    return _form_page(
        request,
        session,
        {},
        {},
        admin,
        action=str(request.url_for("kyc_queue_create")),
        heading="New KYC review",
    )


@router.post("", name="kyc_queue_create")
def create_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    customer_name: Annotated[str, Form()] = "",
    customer_ref: Annotated[str, Form()] = "",
    risk_score: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    submitted_on: Annotated[str, Form()] = "",
    reviewer_id: Annotated[str, Form()] = "",
    notes: Annotated[str, Form()] = "",
):
    auth.require_admin(current_user)
    admin = auth.is_admin(current_user)
    values, errors = _parse(
        {
            "customer_name": customer_name,
            "customer_ref": customer_ref,
            "risk_score": risk_score,
            "status": status,
            "submitted_on": submitted_on,
            "reviewer_id": reviewer_id,
            "notes": notes,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("kyc_queue_create")),
            heading="New KYC review",
            status_code=400,
        )
    row = KycReview(**values)
    audit.insert(session, row)
    return RedirectResponse(
        request.url_for("kyc_queue_detail", kyc_review_id=row.id), status_code=303
    )


@router.get("/{kyc_review_id}", name="kyc_queue_detail")
def detail_row(request: Request, session: DbSession, current_user: CurrentUser, kyc_review_id: int):
    row = _get(session, kyc_review_id)
    admin = auth.is_admin(current_user)
    current_value = row.status
    current = {
        "label": current_value,
        "tone": STATUS_TONES.get(current_value, "neutral"),
    }
    decisions = [
        {"label": option.title(), "value": option, "tone": STATUS_TONES.get(option, "neutral")}
        for option in STATUS_OPTIONS
        if option
        in STATUS_TRANSITIONS.get(
            current_value,
            tuple(option for option in STATUS_OPTIONS if option != current_value),
        )
    ]
    return templates.TemplateResponse(
        request,
        "kyc_queue/detail.html",
        {
            "title": f"{SINGULAR} {row.id}",
            "row_id": row.id,
            "items": _items(row, admin),
            "list_url": str(request.url_for("kyc_queue_list")),
            "edit_url": (
                str(request.url_for("kyc_queue_edit", kyc_review_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "delete_url": (
                str(request.url_for("kyc_queue_delete", kyc_review_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "current": current,
            "decisions": decisions,
            "decision_url": str(request.url_for("kyc_queue_decide", kyc_review_id=row.id)),
            "can_decide": auth.can_write(current_user),
        },
    )


@router.post("/{kyc_review_id}/status", name="kyc_queue_decide")
def decide_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    kyc_review_id: int,
    status: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    row = _get(session, kyc_review_id)
    if status not in STATUS_OPTIONS:
        raise HTTPException(status_code=400, detail="invalid status")
    if status not in STATUS_TRANSITIONS.get(
        row.status,
        tuple(option for option in STATUS_OPTIONS if option != row.status),
    ):
        raise HTTPException(status_code=400, detail="transition not allowed")
    audit.update(session, row, {"status": status})
    return RedirectResponse(request.url_for("kyc_queue_list"), status_code=303)


@router.get("/{kyc_review_id}/edit", name="kyc_queue_edit")
def edit_row(request: Request, session: DbSession, current_user: CurrentUser, kyc_review_id: int):
    admin = auth.is_admin(current_user)
    row = _get(session, kyc_review_id)
    values = {
        "customer_name": row.customer_name,
        "customer_ref": row.customer_ref,
        "risk_score": row.risk_score,
        "status": row.status,
        "submitted_on": row.submitted_on,
        "reviewer_id": row.reviewer_id,
        "notes": row.notes,
    }
    return _form_page(
        request,
        session,
        values,
        {},
        admin,
        action=str(request.url_for("kyc_queue_update", kyc_review_id=row.id)),
        heading=f"Edit KYC review {row.id}",
        writable=auth.can_write(current_user),
        delete_url=str(request.url_for("kyc_queue_delete", kyc_review_id=row.id)),
        detail_url=str(request.url_for("kyc_queue_detail", kyc_review_id=row.id)),
    )


@router.post("/{kyc_review_id}", name="kyc_queue_update")
def update_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    kyc_review_id: int,
    customer_name: Annotated[str, Form()] = "",
    customer_ref: Annotated[str, Form()] = "",
    risk_score: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    submitted_on: Annotated[str, Form()] = "",
    reviewer_id: Annotated[str, Form()] = "",
    notes: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    row = _get(session, kyc_review_id)
    values, errors = _parse(
        {
            "customer_name": customer_name,
            "customer_ref": customer_ref,
            "risk_score": risk_score,
            "status": status,
            "submitted_on": submitted_on,
            "reviewer_id": reviewer_id,
            "notes": notes,
        },
        admin,
    )
    _check_references(session, values, errors)
    if (
        WORKFLOW_FIELD in values
        and values[WORKFLOW_FIELD] != row.status
        and values[WORKFLOW_FIELD]
        not in STATUS_TRANSITIONS.get(
            row.status,
            tuple(option for option in STATUS_OPTIONS if option != row.status),
        )
    ):
        errors[WORKFLOW_FIELD] = "transition not allowed"
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("kyc_queue_update", kyc_review_id=row.id)),
            heading=f"Edit KYC review {row.id}",
            delete_url=str(request.url_for("kyc_queue_delete", kyc_review_id=row.id)),
            detail_url=str(request.url_for("kyc_queue_detail", kyc_review_id=row.id)),
            status_code=400,
        )
    audit.update(session, row, values)
    return RedirectResponse(
        request.url_for("kyc_queue_detail", kyc_review_id=row.id), status_code=303
    )


@router.post("/{kyc_review_id}/delete", name="kyc_queue_delete")
def delete_row(request: Request, session: DbSession, current_user: CurrentUser, kyc_review_id: int):
    auth.require_write(current_user)
    row = _get(session, kyc_review_id)
    audit.delete(session, row)
    return RedirectResponse(request.url_for("kyc_queue_list"), status_code=303)
