"""The refunds app.

Generated by scaffold/generate.py from specs/refunds.yaml.
Edit freely: regenerating keeps any file you have changed.
Creating a row is admin-only: customer_ref are required but hidden from other roles.
"""
