"""Refunds dashboard screens.

Generated by scaffold/generate.py from specs/refunds.yaml.
Edit freely: regenerating keeps any file you have changed.
Creating a row is admin-only: customer_ref are required but hidden from other roles.
"""

from datetime import UTC, datetime
from typing import Annotated
from urllib.parse import urlencode

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import func, or_, select
from sqlalchemy.orm import Session

from apps.refunds.model import STATUS_OPTIONS, STATUS_TONES, STATUS_TRANSITIONS, Refund
from foundation import audit, auth, forms
from foundation.deps import CurrentUser, DbSession
from foundation.models import AuditLog, User
from foundation.templating import templates

TITLE = "Refunds dashboard"
DESCRIPTION = "Customer refund requests waiting for approval and processing."
SINGULAR = "refund"
MODEL = Refund
_SEARCHABLE = (
    "transaction_ref",
    "currency",
    "reason",
)
_ADMIN_SEARCHABLE = ("customer_ref",)
_SORTABLE = (
    "transaction_ref",
    "amount",
    "currency",
    "reason",
    "status",
    "requested_on",
    "id",
)
_ADMIN_SORTABLE = (
    *_SORTABLE,
    "customer_ref",
)
WORKFLOW_FIELD = "status"
OPEN_STATES = ("pending",)
STATUS_CLOSED = (
    "approved",
    "denied",
    "processed",
)

router = APIRouter(prefix="/refunds", tags=["refunds"])


def _get(session: Session, refund_id: int) -> Refund:
    row = session.get(Refund, refund_id)
    if row is None:
        raise HTTPException(status_code=404, detail="Refunds dashboard: no such row")
    return row


def _columns(
    request: Request,
    admin: bool,
    *,
    state: str | None,
    q: str,
    sort: str,
    direction: str,
) -> list[dict[str, object]]:
    """What the list view shows. Sensitive columns never reach a non-admin."""
    columns = []
    columns.append(
        {
            "key": "transaction_ref",
            "label": "Transaction ref",
            "kind": ("link" if not columns else "text"),
        }
    )
    if admin:
        columns.append(
            {
                "key": "customer_ref",
                "label": "Customer ref",
                "kind": ("link" if not columns else "text"),
            }
        )
    columns.append(
        {"key": "amount", "label": "Amount", "kind": ("link" if not columns else "number")}
    )
    columns.append(
        {"key": "currency", "label": "Currency", "kind": ("link" if not columns else "text")}
    )
    columns.append(
        {"key": "reason", "label": "Reason", "kind": ("link" if not columns else "text")}
    )
    columns.append(
        {"key": "status", "label": "Status", "kind": ("link" if not columns else "badge")}
    )
    columns.append(
        {
            "key": "requested_on",
            "label": "Requested on",
            "kind": ("link" if not columns else "date"),
        }
    )
    columns.append(
        {"key": "approver", "label": "Approver", "kind": ("link" if not columns else "text")}
    )
    columns.append({"key": "id", "label": "ID", "kind": "id"})
    sortable = _ADMIN_SORTABLE if admin else _SORTABLE
    for column in columns:
        key = column["key"]
        if key not in sortable:
            continue
        next_direction = "desc" if sort == key and direction == "asc" else "asc"
        params = {"sort": key, "dir": next_direction}
        if state is not None:
            params["state"] = state
        if q:
            params["q"] = q
        column["sort_href"] = f"{request.url.path}?{urlencode(params)}"
        if sort == key:
            column["sorted"] = direction
    return columns


def _row(request: Request, row: Refund, admin: bool) -> dict[str, object]:
    data: dict[str, object] = {
        "transaction_ref": forms.display(row.transaction_ref),
        "amount": forms.display(row.amount),
        "currency": forms.display(row.currency),
        "reason": forms.display(row.reason),
        "status": (
            None
            if row.status is None
            else {
                "label": forms.display(row.status),
                "tone": STATUS_TONES.get(row.status, "neutral"),
            }
        ),
        "requested_on": forms.display(row.requested_on),
        "approver": forms.display(row.approver.display_name if row.approver else None),
    }
    if admin:
        data["customer_ref"] = forms.display(row.customer_ref)
    ordered = {
        key: data[key]
        for key in [
            "transaction_ref",
            "customer_ref",
            "amount",
            "currency",
            "reason",
            "status",
            "requested_on",
            "approver",
        ]
        if key in data
    }
    if ordered:
        first_key = next(iter(ordered))
        first_value = ordered[first_key]
        ordered[first_key] = {
            "label": first_value["label"] if isinstance(first_value, dict) else first_value,
            "href": str(request.url_for("refunds_detail", refund_id=row.id)),
        }
    ordered["id"] = row.id
    ordered["edit_url"] = str(request.url_for("refunds_edit", refund_id=row.id))
    return ordered


def _items(row: Refund, admin: bool) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    items.append({"label": "Transaction ref", "value": forms.display(row.transaction_ref)})
    if admin:
        items.append({"label": "Customer ref", "value": forms.display(row.customer_ref)})
    items.append({"label": "Amount", "value": forms.display(row.amount)})
    items.append({"label": "Currency", "value": forms.display(row.currency)})
    items.append({"label": "Reason", "value": forms.display(row.reason)})
    items.append(
        {
            "label": "Status",
            "value": (
                None
                if row.status is None
                else {
                    "label": forms.display(row.status),
                    "tone": STATUS_TONES.get(row.status, "neutral"),
                }
            ),
            "kind": "badge",
        }
    )
    items.append({"label": "Requested on", "value": forms.display(row.requested_on)})
    items.append(
        {
            "label": "Approver",
            "value": forms.display(row.approver.display_name if row.approver else None),
        }
    )
    return items


def _fields(session: Session, values: dict[str, object], admin: bool) -> list[dict[str, object]]:
    """Form fields for the generic partial. Sensitive fields are admin-only."""
    fields: list[dict[str, object]] = [
        {
            "name": "transaction_ref",
            "label": "Transaction ref",
            "value": values.get("transaction_ref"),
            "required": True,
            "type": "text",
        },
        {
            "name": "amount",
            "label": "Amount",
            "value": values.get("amount"),
            "required": True,
            "type": "number",
            "step": "any",
        },
        {
            "name": "currency",
            "label": "Currency",
            "value": values.get("currency"),
            "required": True,
            "type": "text",
        },
        {
            "name": "reason",
            "label": "Reason",
            "value": values.get("reason"),
            "required": False,
            "type": "text",
        },
        {
            "name": "status",
            "label": "Status",
            "value": values.get("status"),
            "required": True,
            "type": "select",
            "options": [{"value": option, "label": option} for option in STATUS_OPTIONS],
        },
        {
            "name": "requested_on",
            "label": "Requested on",
            "value": values.get("requested_on"),
            "required": False,
            "type": "date",
        },
        {
            "name": "approver_id",
            "label": "Approver",
            "value": values.get("approver_id"),
            "required": False,
            "type": "select",
            "options": [{"value": "", "label": "—"}]
            + forms.as_options(
                session.scalars(select(User).order_by(User.display_name)), "id", "display_name"
            ),
        },
    ]
    if admin:
        fields.extend(
            [
                {
                    "name": "customer_ref",
                    "label": "Customer ref",
                    "value": values.get("customer_ref"),
                    "required": True,
                    "type": "text",
                },
            ]
        )
    workflow_value = values.get(WORKFLOW_FIELD)
    if workflow_value in STATUS_OPTIONS:
        workflow_options = (
            workflow_value,
            *STATUS_TRANSITIONS.get(
                workflow_value,
                tuple(option for option in STATUS_OPTIONS if option != workflow_value),
            ),
        )
        for field in fields:
            if field["name"] == WORKFLOW_FIELD:
                field["options"] = [
                    {"value": option, "label": option} for option in workflow_options
                ]
    return fields


#: Foreign keys to check before writing: (column, table, model).
_REFERENCES = (("approver_id", "user", User),)


def _check_references(session: Session, values: dict[str, object], errors: dict[str, str]) -> None:
    """A well-formed id pointing at nothing is a bad request, not an IntegrityError."""
    for column, table, model in _REFERENCES:
        value = values.get(column)
        if value is not None and session.get(model, value) is None:
            errors[column] = f"no such {table}"


def _parse(raw: dict[str, str | None], admin: bool) -> tuple[dict[str, object], dict[str, str]]:
    values: dict[str, object] = {}
    errors: dict[str, str] = {}
    forms.collect(
        values,
        errors,
        "transaction_ref",
        forms.text,
        raw.get("transaction_ref"),
        required=True,
        max_length=255,
    )
    forms.collect(values, errors, "amount", forms.number, raw.get("amount"), required=True)
    forms.collect(
        values, errors, "currency", forms.text, raw.get("currency"), required=True, max_length=255
    )
    forms.collect(values, errors, "reason", forms.text, raw.get("reason"), max_length=255)
    forms.collect(
        values,
        errors,
        "status",
        forms.choice,
        raw.get("status"),
        options=STATUS_OPTIONS,
        required=True,
    )
    forms.collect(values, errors, "requested_on", forms.day, raw.get("requested_on"))
    forms.collect(values, errors, "approver_id", forms.reference, raw.get("approver_id"))
    if admin:
        forms.collect(
            values,
            errors,
            "customer_ref",
            forms.text,
            raw.get("customer_ref"),
            required=True,
            max_length=255,
        )
    return values, errors


def _form_page(
    request: Request,
    session: Session,
    values: dict[str, object],
    errors: dict[str, str],
    admin: bool,
    *,
    action: str,
    heading: str,
    writable: bool = True,
    delete_url: str | None = None,
    detail_url: str | None = None,
    row_id: int | None = None,
    status_code: int = 200,
):
    return templates.TemplateResponse(
        request,
        "refunds/form.html",
        {
            "title": heading,
            "heading": heading,
            "action": action,
            "fields": _fields(session, values, admin),
            "errors": errors,
            "submit_label": "Save" if writable else None,
            "list_url": str(request.url_for("refunds_list")),
            "delete_url": delete_url if writable else None,
            "detail_url": detail_url,
            "row_id": row_id,
        },
        status_code=status_code,
    )


@router.get("", name="refunds_list")
def list_rows(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    state: str = "",
    q: str = "",
    sort: str = "",
    dir: str = "asc",
):
    admin = auth.is_admin(current_user)
    q = q.strip()
    searchable = _SEARCHABLE + (_ADMIN_SEARCHABLE if admin else ())
    sortable = _ADMIN_SORTABLE if admin else _SORTABLE
    normalized_sort = sort if sort in sortable else ""
    normalized_dir = dir if dir in {"asc", "desc"} else "asc"
    query = select(MODEL)
    if q and searchable:
        pattern = f"%{q}%"
        query = query.where(or_(*(getattr(MODEL, column).ilike(pattern) for column in searchable)))
    workflow_column = getattr(MODEL, WORKFLOW_FIELD)
    grouped = dict(
        session.execute(select(workflow_column, func.count()).group_by(workflow_column)).all()
    )
    open_count = sum(grouped.get(option, 0) for option in OPEN_STATES)
    total = sum(grouped.values())
    if state == "":
        query = query.where(workflow_column.in_(OPEN_STATES))
    elif state == "all":
        pass
    elif state in STATUS_OPTIONS:
        query = query.where(workflow_column == state)
    else:
        raise HTTPException(status_code=400, detail="invalid state")
    list_url = str(request.url_for("refunds_list"))
    tabs = [
        {"label": "Needs decision", "href": list_url, "count": open_count, "active": state == ""}
    ]
    tabs.extend(
        {
            "label": option.title(),
            "href": f"{list_url}?{urlencode({'state': option})}",
            "count": grouped.get(option, 0),
            "active": state == option,
        }
        for option in STATUS_OPTIONS
    )
    tabs.append(
        {
            "label": "All",
            "href": f"{list_url}?state=all",
            "count": total,
            "active": state == "all",
        }
    )
    today_start = datetime.now(UTC).replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=None)
    decided_today = sum(
        1
        for entry in session.scalars(
            select(AuditLog).where(
                AuditLog.table_name == MODEL.__tablename__,
                AuditLog.action == AuditLog.ACTION_UPDATE,
                AuditLog.created_at >= today_start,
            )
        )
        if (entry.after or {}).get(WORKFLOW_FIELD) in STATUS_CLOSED
        and (entry.before or {}).get(WORKFLOW_FIELD) not in STATUS_CLOSED
        and (entry.after or {}).get(WORKFLOW_FIELD) != (entry.before or {}).get(WORKFLOW_FIELD)
    )
    if normalized_sort:
        sort_column = getattr(MODEL, normalized_sort)
        query = query.order_by(sort_column.asc() if normalized_dir == "asc" else sort_column.desc())
    elif state == "":
        query = query.order_by(MODEL.id.asc())
    else:
        query = query.order_by(MODEL.id.desc())
    rows = session.scalars(query).all()
    new_url = str(request.url_for("refunds_new")) if auth.is_admin(current_user) else None
    return templates.TemplateResponse(
        request,
        "refunds/list.html",
        {
            "title": TITLE,
            "columns": _columns(
                request,
                admin,
                state=state,
                q=q,
                sort=normalized_sort,
                direction=normalized_dir,
            ),
            "rows": [_row(request, row, admin) for row in rows],
            "actions": [{"label": "Edit", "href_key": "edit_url"}],
            "description": DESCRIPTION,
            "list_url": str(request.url_for("refunds_list")),
            "searchable": bool(_SEARCHABLE or (_ADMIN_SEARCHABLE if admin else ())),
            "q": q,
            "sort": normalized_sort,
            "dir": normalized_dir,
            "state": state,
            "empty": {
                "title": (
                    "Nothing needs a decision" if state == "" else "No refunds dashboard yet"
                ),
                "text": (
                    f"New {SINGULAR} will appear here when they arrive."
                    if state == ""
                    else DESCRIPTION or None
                ),
                "cta": {"label": "New refund", "href": new_url} if new_url else None,
            },
            "new_url": new_url,
            "stats": [
                {"label": "Waiting", "value": open_count},
                {"label": "Decided today", "value": decided_today},
                {"label": "Total", "value": total},
            ],
            "tabs": tabs,
        },
    )


@router.get("/new", name="refunds_new")
def new_row(request: Request, session: DbSession, current_user: CurrentUser):
    auth.require_admin(current_user)
    admin = auth.is_admin(current_user)
    return _form_page(
        request,
        session,
        {},
        {},
        admin,
        action=str(request.url_for("refunds_create")),
        heading="New refund",
    )


@router.post("", name="refunds_create")
def create_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    transaction_ref: Annotated[str, Form()] = "",
    customer_ref: Annotated[str, Form()] = "",
    amount: Annotated[str, Form()] = "",
    currency: Annotated[str, Form()] = "",
    reason: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    requested_on: Annotated[str, Form()] = "",
    approver_id: Annotated[str, Form()] = "",
):
    auth.require_admin(current_user)
    admin = auth.is_admin(current_user)
    values, errors = _parse(
        {
            "transaction_ref": transaction_ref,
            "customer_ref": customer_ref,
            "amount": amount,
            "currency": currency,
            "reason": reason,
            "status": status,
            "requested_on": requested_on,
            "approver_id": approver_id,
        },
        admin,
    )
    _check_references(session, values, errors)
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("refunds_create")),
            heading="New refund",
            status_code=400,
        )
    row = Refund(**values)
    audit.insert(session, row)
    return RedirectResponse(request.url_for("refunds_detail", refund_id=row.id), status_code=303)


@router.get("/{refund_id}", name="refunds_detail")
def detail_row(request: Request, session: DbSession, current_user: CurrentUser, refund_id: int):
    row = _get(session, refund_id)
    admin = auth.is_admin(current_user)
    current_value = row.status
    current = {
        "label": current_value,
        "tone": STATUS_TONES.get(current_value, "neutral"),
    }
    decisions = [
        {"label": option.title(), "value": option, "tone": STATUS_TONES.get(option, "neutral")}
        for option in STATUS_OPTIONS
        if option
        in STATUS_TRANSITIONS.get(
            current_value,
            tuple(option for option in STATUS_OPTIONS if option != current_value),
        )
    ]
    return templates.TemplateResponse(
        request,
        "refunds/detail.html",
        {
            "title": f"{SINGULAR} {row.id}",
            "row_id": row.id,
            "items": _items(row, admin),
            "list_url": str(request.url_for("refunds_list")),
            "edit_url": (
                str(request.url_for("refunds_edit", refund_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "delete_url": (
                str(request.url_for("refunds_delete", refund_id=row.id))
                if auth.can_write(current_user)
                else None
            ),
            "current": current,
            "decisions": decisions,
            "decision_url": str(request.url_for("refunds_decide", refund_id=row.id)),
            "can_decide": auth.can_write(current_user),
        },
    )


@router.post("/{refund_id}/status", name="refunds_decide")
def decide_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    refund_id: int,
    status: Annotated[str, Form()] = "",
    expected: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    row = _get(session, refund_id)
    if expected and expected != row.status:
        raise HTTPException(
            status_code=409,
            detail=(
                f"this {SINGULAR} was already moved to {row.status} "
                "by someone else; reload to see it"
            ),
        )
    if status not in STATUS_OPTIONS:
        raise HTTPException(status_code=400, detail="invalid status")
    if status not in STATUS_TRANSITIONS.get(
        row.status,
        tuple(option for option in STATUS_OPTIONS if option != row.status),
    ):
        raise HTTPException(status_code=400, detail="transition not allowed")
    audit.update(session, row, {"status": status})
    return RedirectResponse(request.url_for("refunds_list"), status_code=303)


@router.get("/{refund_id}/edit", name="refunds_edit")
def edit_row(request: Request, session: DbSession, current_user: CurrentUser, refund_id: int):
    admin = auth.is_admin(current_user)
    row = _get(session, refund_id)
    values = {
        "transaction_ref": row.transaction_ref,
        "customer_ref": row.customer_ref,
        "amount": row.amount,
        "currency": row.currency,
        "reason": row.reason,
        "status": row.status,
        "requested_on": row.requested_on,
        "approver_id": row.approver_id,
    }
    return _form_page(
        request,
        session,
        values,
        {},
        admin,
        action=str(request.url_for("refunds_update", refund_id=row.id)),
        heading=f"Edit refund {row.id}",
        writable=auth.can_write(current_user),
        delete_url=str(request.url_for("refunds_delete", refund_id=row.id)),
        detail_url=str(request.url_for("refunds_detail", refund_id=row.id)),
        row_id=row.id,
    )


@router.post("/{refund_id}", name="refunds_update")
def update_row(
    request: Request,
    session: DbSession,
    current_user: CurrentUser,
    refund_id: int,
    transaction_ref: Annotated[str, Form()] = "",
    customer_ref: Annotated[str, Form()] = "",
    amount: Annotated[str, Form()] = "",
    currency: Annotated[str, Form()] = "",
    reason: Annotated[str, Form()] = "",
    status: Annotated[str, Form()] = "",
    requested_on: Annotated[str, Form()] = "",
    approver_id: Annotated[str, Form()] = "",
):
    auth.require_write(current_user)
    admin = auth.is_admin(current_user)
    row = _get(session, refund_id)
    values, errors = _parse(
        {
            "transaction_ref": transaction_ref,
            "customer_ref": customer_ref,
            "amount": amount,
            "currency": currency,
            "reason": reason,
            "status": status,
            "requested_on": requested_on,
            "approver_id": approver_id,
        },
        admin,
    )
    _check_references(session, values, errors)
    if (
        WORKFLOW_FIELD in values
        and values[WORKFLOW_FIELD] != row.status
        and values[WORKFLOW_FIELD]
        not in STATUS_TRANSITIONS.get(
            row.status,
            tuple(option for option in STATUS_OPTIONS if option != row.status),
        )
    ):
        errors[WORKFLOW_FIELD] = "transition not allowed"
    if errors:
        return _form_page(
            request,
            session,
            values,
            errors,
            admin,
            action=str(request.url_for("refunds_update", refund_id=row.id)),
            heading=f"Edit refund {row.id}",
            delete_url=str(request.url_for("refunds_delete", refund_id=row.id)),
            detail_url=str(request.url_for("refunds_detail", refund_id=row.id)),
            row_id=row.id,
            status_code=400,
        )
    audit.update(session, row, values)
    return RedirectResponse(request.url_for("refunds_detail", refund_id=row.id), status_code=303)


@router.post("/{refund_id}/delete", name="refunds_delete")
def delete_row(request: Request, session: DbSession, current_user: CurrentUser, refund_id: int):
    auth.require_write(current_user)
    row = _get(session, refund_id)
    audit.delete(session, row)
    return RedirectResponse(request.url_for("refunds_list"), status_code=303)
